ProgrammableWaveData_1::
	.incbin "sound/programmable_wave_samples/01.pcm"

ProgrammableWaveData_2::
	.incbin "sound/programmable_wave_samples/02.pcm"

ProgrammableWaveData_3::
	.incbin "sound/programmable_wave_samples/03.pcm"

ProgrammableWaveData_4::
	.incbin "sound/programmable_wave_samples/04.pcm"

ProgrammableWaveData_5::
	.incbin "sound/programmable_wave_samples/05.pcm"

ProgrammableWaveData_6::
	.incbin "sound/programmable_wave_samples/06.pcm"

ProgrammableWaveData_7::
	.incbin "sound/programmable_wave_samples/07.pcm"

ProgrammableWaveData_8::
	.incbin "sound/programmable_wave_samples/08.pcm"

ProgrammableWaveData_9::
	.incbin "sound/programmable_wave_samples/09.pcm"

ProgrammableWaveData_10::
	.incbin "sound/programmable_wave_samples/10.pcm"

ProgrammableWaveData_11::
	.incbin "sound/programmable_wave_samples/11.pcm"

ProgrammableWaveData_RSE1::
	.incbin "sound/programmable_wave_samples/rse01.pcm"

ProgrammableWaveData_RSE2::
	.incbin "sound/programmable_wave_samples/rse02.pcm"

ProgrammableWaveData_RSE3::
	.incbin "sound/programmable_wave_samples/rse03.pcm"

ProgrammableWaveData_RSE4::
	.incbin "sound/programmable_wave_samples/rse04.pcm"

ProgrammableWaveData_RSE5::
	.incbin "sound/programmable_wave_samples/rse05.pcm"

ProgrammableWaveData_RSE6::
	.incbin "sound/programmable_wave_samples/rse06.pcm"

ProgrammableWaveData_RSE7::
	.incbin "sound/programmable_wave_samples/rse07.pcm"

ProgrammableWaveData_RSE8::
	.incbin "sound/programmable_wave_samples/rse08.pcm"

ProgrammableWaveData_RSE9::
	.incbin "sound/programmable_wave_samples/rse09.pcm"

ProgrammableWaveData_RSE10::
	.incbin "sound/programmable_wave_samples/rse10.pcm"

ProgrammableWaveData_RSE11::
	.incbin "sound/programmable_wave_samples/rse11.pcm"

ProgrammableWaveData_RSE12::
	.incbin "sound/programmable_wave_samples/rse12.pcm"

ProgrammableWaveData_RSE13::
	.incbin "sound/programmable_wave_samples/rse13.pcm"

ProgrammableWaveData_RSE14::
	.incbin "sound/programmable_wave_samples/rse14.pcm"

ProgrammableWaveData_RSE15::
	.incbin "sound/programmable_wave_samples/rse15.pcm"

ProgrammableWaveData_RSE16::
	.incbin "sound/programmable_wave_samples/rse16.pcm"

ProgrammableWaveData_RSE17::
	.incbin "sound/programmable_wave_samples/rse17.pcm"

ProgrammableWaveData_RSE18::
	.incbin "sound/programmable_wave_samples/rse18.pcm"

ProgrammableWaveData_RSE19::
	.incbin "sound/programmable_wave_samples/rse19.pcm"

ProgrammableWaveData_RSE20::
	.incbin "sound/programmable_wave_samples/rse20.pcm"

ProgrammableWaveData_RSE21::
	.incbin "sound/programmable_wave_samples/rse21.pcm"

ProgrammableWaveData_RSE22::
	.incbin "sound/programmable_wave_samples/rse22.pcm"

ProgrammableWaveData_RSE23::
	.incbin "sound/programmable_wave_samples/rse23.pcm"

ProgrammableWaveData_RSE24::
	.incbin "sound/programmable_wave_samples/rse24.pcm"

ProgrammableWaveData_RSE25::
	.incbin "sound/programmable_wave_samples/rse25.pcm"

ProgrammableWaveData_sq25half:: @ 25% square half
	.incbin "sound/programmable_wave_samples/sq25half.pcm"

ProgrammableWaveData_sq50half:: @ 50% square half
	.incbin "sound/programmable_wave_samples/sq50half.pcm"

ProgrammableWaveData_sq50oct:: @ 50% square oct lower
	.incbin "sound/programmable_wave_samples/sq50oct.pcm"

ProgrammableWaveData_sq37half:: @ 37.5% square half
	.incbin "sound/programmable_wave_samples/sq37half.pcm"
