	.align 2
voicegroup901::
	voice_keysplit_all voicegroup502                                                      @ 000 | Direct | RSE Drum 1 | VVVVV
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 7, 3                                            @ 001 | GB Square1 | Spring Lane Ch. 1
	voice_square_2_alt 60, 0, 3, 0, 2, 7, 3                                               @ 002 | GB Square2 | Spring Lane Ch. 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_5, 0, 2, 7, 3                 @ 003 | GB Wave    | Spring Lane Ch. 3
	voice_square_1_alt 60, 0, 0, 2, 0, 1, 5, 2                                            @ 004 | GB Square1 | Plain Asia Ch. 1
	voice_square_2_alt 60, 0, 3, 0, 2, 7, 4                                               @ 005 | GB Square2 | Plain Asia Ch. 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_6, 0, 7, 15, 0                @ 006 | GB Wave    | Plain Asia Ch. 3
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 7, 3                                            @ 007 | GB Square1 | Girls' Sealing Club Ch. 1
	voice_square_2_alt 60, 0, 3, 0, 2, 7, 3                                               @ 008 | GB Square2 | Girls' Sealing Club Ch. 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_5, 0, 2, 7, 3                 @ 009 | GB Wave    | Girls' Sealing Club Ch. 3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 010 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 011 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 012 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 013 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 014 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 015 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 016 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 017 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 018 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 019 | ---
	voice_square_1_alt 60, 0, 0, 0, 0, 2, 5, 2                                            @ 020 | GB Square1 | Master Spark GBC Ch. 1.1 duty_cycle 3 vibrato 18, 1, 5 note_type 12, 9, 2
	voice_square_1_alt 60, 0, 0, 3, 0, 2, 7, 3                                            @ 021 | GB Square1 | Master Spark GBC Ch. 1.2 duty_cycle 3 vibrato 0, 0, 0 note_type 12, 10, 3
	voice_square_2_alt 60, 0, 3, 0, 2, 7, 3                                               @ 022 | GB Square2 | Master Spark GBC Ch. 2 duty_cycle 1 vibrato 8, 3, 6 note_type 12, 12, 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_5, 0, 2, 7, 3                 @ 023 | GB Wave    | Master Spark GBC Ch. 3.1 vibrato 0, 0, 0 note_type 12, 1, 9
	voice_square_1_alt 60, 0, 0, 2, 0, 1, 5, 2                                            @ 024 | GB Square1 | Reincarnation GBC Ch. 1
	voice_square_2_alt 60, 0, 3, 0, 2, 7, 4                                               @ 025 | GB Square2 | Reincarnation GBC Ch. 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_6, 0, 7, 15, 0                @ 026 | GB Wave    | Reincarnation GBC Ch. 3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 027 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 028 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 029 | ---
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 7, 3                                            @ 030 | GB Square1 | Faith is for the Transient People GBC Ch. 1
	voice_square_2_alt 60, 0, 3, 0, 2, 7, 3                                               @ 031 | GB Square2 | Faith is for the Transient People GBC Ch. 2.1
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_5, 0, 2, 7, 3                 @ 032 | GB Wave    | Faith is for the Transient People GBC Ch. 3
	voice_square_2_alt 60, 0, 2, 0, 1, 5, 2                                               @ 033 | GB Square2 | Faith is for the Transient People GBC Ch. 2.2
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 7, 3                                            @ 034 | GB Square1 | Street GBC Ch. 1
	voice_square_2_alt 60, 0, 3, 0, 2, 7, 3                                               @ 035 | GB Square2 | Street GBC Ch. 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_5, 0, 2, 7, 3                 @ 036 | GB Wave    | Street GBC Ch. 3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 037 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 038 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 039 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 040 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 041 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 042 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 043 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 044 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 045 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 046 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 047 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 048 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 049 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 050 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 051 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 052 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 053 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 054 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 055 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 056 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 057 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 058 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 059 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 060 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 061 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 062 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 063 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 064 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 065 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 066 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 067 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 068 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 069 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 070 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 071 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 072 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 073 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 074 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 075 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 076 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 077 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 078 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 079 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 080 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 081 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 082 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 083 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 084 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 085 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 086 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 087 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 088 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 089 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 090 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 091 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 092 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 093 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 094 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 095 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 096 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 097 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 098 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 099 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 100 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 101 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 102 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 103 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 104 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 105 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 106 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 107 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 108 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 109 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 110 | ---
	voice_square_1_alt 60, 0, 0, 2, 0, 1, 5, 2                                            @ 111 | GB Square1 | Generic GBC Ch. 1
	voice_square_2_alt 60, 0, 3, 0, 2, 7, 4                                               @ 112 | GB Square2 | Generic GBC Ch. 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_6, 0, 7, 15, 0                @ 113 | GB Wave    | Generic GBC Ch. 3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 114 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 115 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 116 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 117 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 118 | ---
	voice_directsound 60, 0, DirectSoundWaveData_dp_reverscyn_16, 255, 0, 255, 16         @ 119 | Direct | HGSS Reverse Cymbal
	voice_keysplit_all voicegroup230                                                      @ 120 | Direct | Drum | HGSS Drum | VVVVV
	voice_keysplit_all voicegroup231                                                      @ 121 | Direct | Drum | HGSS Taiko Drum
	voice_keysplit_all voicegroup232                                                      @ 122 | Direct | Drum | HGSS synth kick+snare
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 123 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 124 | ---
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 125 | ---
	voice_noise_alt 60, 0, 0, 0, 2, 6, 2                                                  @ 126 | Noise | RSE Noise 2
	voice_noise_alt 60, 0, 0, 0, 1, 6, 0                                                  @ 127 | Noise | RSE Noise 1
