SaffronCity_MrPsychicsHouse_Text_YouWantedThis::
    .string "...Wait! Don't\n"
    .string "say a word!\p"
    .string "You wanted this!$"

SaffronCity_MrPsychicsHouse_Text_ReceivedTM29FromMrPsychic::
    .string "{PLAYER} received\n"
    .string "TM29!$"

SaffronCity_MrPsychicsHouse_Text_ExplainTM29::
    .string "TM29 is PSYCHIC!\p"
    .string "It's can lower the\n"
    .string "target's SPECIAL\l"
    .string "abilities.$"

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom::
    .string "Where do you plan\n"
    .string "to put this?$"

