SafariZone_East_Text_HowManyDidYouCatch::
    .string "How many did you\n"
    .string "catch? Iá bushed\l"
    .string "from the work!$"

SafariZone_East_Text_CaughtChanseyAllWorthwhile::
    .string "I caught a\n"
    .string "CHANSEY!\p"
    .string "That makes this\n"
    .string "all worthwhile!$"

SafariZone_East_Text_TiredFromAllTheFun::
    .string "Whew! Iá tired\n"
    .string "from all the fun!$"

