FuchsiaCity_House1_Text_WardenIsOldHasFalseTeeth::
    .string "SAFARI ZONEÙ\n"
    .string "WARDEN is old,\l"
    .string "but still active!\p"
    .string "All his teeth are\n"
    .string "false, though.$"

FuchsiaCity_House1_Text_BillIsMyGrandson::
    .string "Hmm? Youße met\n"
    .string "BILL?\p"
    .string "HeÙ my grandson!\p"
    .string "He always liked\n"
    .string "collecting things\l"
    .string "even as a child!$"

FuchsiaCity_House1_Text_BillFilesHisOwnMonData::
    .string "BILL files his\n"
    .string "own POKéMON data\l"
    .string "on his PC!\p"
    .string "Did he show you?$"

