SSAnne_Kitchen_Text_BusyOutOfTheWay::
    .string "You, mon petit!\n"
    .string "We're busy here!\l"
    .string "Out of the way!$"

SSAnne_Kitchen_Text_SawOddBerryInTrash::
    .string "I saw an odd ball in the trash.$"

SSAnne_Kitchen_Text_SoBusyImDizzy::
    .string "I'm so busy I'm getting dizzy!$"

SSAnne_Kitchen_Text_PeelSpudsEveryDay::
    .string "Hum-de-hum-de-ho...\p"
    .string "I peel spuds every day!\n"
    .string "Hum-hum...$"

SSAnne_Kitchen_Text_HearAboutSnorlaxItsAGlutton::
    .string "Did you hear about SNORLAX?\n"
    .string "All it does is eat and sleep!$"

SSAnne_Kitchen_Text_OnlyGetToPeelOnions::
    .string "Snivel...Sniff...\p"
    .string "I only get to peel onions...\n"
    .string "Snivel...$"

SSAnne_Kitchen_Text_IAmLeChefMainCourseIs::
    .string "Er-hem!\n"
    .string "Indeed I am le CHEF!\p"
    .string "Le main course is$"

SSAnne_Kitchen_Text_SalmonDuSalad::
    .string "Salmon du Salad!\p"
    .string "Les guests may gripe it's\n"
    .string "fish again, however!$"

SSAnne_Kitchen_Text_EelsAuBarbecue::
    .string "Eels au Barbecue!\p"
    .string "Les guests will mutiny, I fear.$"

SSAnne_Kitchen_Text_PrimeBeefsteak::
    .string "Prime Beefsteak!\p"
    .string "But, have I enough fillets du\n"
    .string "beef?$"

