#ifndef GUARD_CONSTANTS_SONGS_H
#define GUARD_CONSTANTS_SONGS_H

#define MUS_DUMMY                 0   // MUS_DUMMY
#define SE_USE_ITEM               1   // SE_KAIFUKU
#define SE_PC_LOGIN               2   // SE_PC_LOGIN
#define SE_PC_OFF                 3   // SE_PC_OFF
#define SE_PC_ON                  4   // SE_PC_ON
#define SE_SELECT                 5   // SE_SELECT
#define SE_WIN_OPEN               6   // SE_WIN_OPEN
#define SE_WALL_HIT               7   // SE_WALL_HIT
#define SE_RS_DOOR                8   // SE_DOOR
#define SE_EXIT                   9   // SE_KAIDAN
#define SE_LEDGE                  10  // SE_DANSA
#define SE_BIKE_BELL              11  // SE_JITENSYA
#define SE_NOT_EFFECTIVE          12  // SE_KOUKA_L
#define SE_EFFECTIVE              13  // SE_KOUKA_M
#define SE_SUPER_EFFECTIVE        14  // SE_KOUKA_H
#define SE_BALL_OPEN              15  // SE_BOWA2
#define SE_FAINT                  16  // SE_POKE_DEAD
#define SE_FLEE                   17  // SE_NIGERU
#define SE_SLIDING_DOOR           18  // SE_JIDO_DOA
#define SE_SHIP                   19  // SE_NAMINORI
#define SE_BANG                   20  // SE_BAN
#define SE_PIN                    21  // SE_PIN
#define SE_BOO                    22  // SE_BOO
#define SE_BALL                   23  // SE_BOWA
#define SE_CONTEST_PLACE          24  // SE_JYUNI
#define SE_SUCCESS                25  // SE_SEIKAI
#define SE_FAILURE                26  // SE_HAZURE
#define SE_EXP                    27  // SE_EXP
#define SE_BIKE_HOP               28  // SE_JITE_PYOKO
#define SE_SWITCH                 29  // SE_MU_PACHI
#define SE_CLICK                  30  // SE_TK_KASYA
#define SE_FU_ZAKU                31  // SE_FU_ZAKU
#define SE_CONTEST_CONDITION_LOSE 32  // SE_FU_ZAKU2
#define SE_LAVARIDGE_FALL_WARP    33  // SE_FU_ZUZUZU
#define SE_ICE_STAIRS             34  // SE_RU_GASHIN
#define SE_ICE_BREAK              35  // SE_RU_GASYAN
#define SE_ICE_CRACK              36  // SE_RU_BARI
#define SE_FALL                   37  // SE_RU_HYUU
#define SE_UNLOCK                 38  // SE_KI_GASYAN
#define SE_WARP_IN                39  // SE_TK_WARPIN
#define SE_WARP_OUT               40  // SE_TK_WARPOUT
#define SE_REPEL                  41  // SE_TU_SAA
#define SE_ROTATING_GATE          42  // SE_HI_TURUN
#define SE_TRUCK_MOVE             43  // SE_TRACK_MOVE
#define SE_TRUCK_STOP             44  // SE_TRACK_STOP
#define SE_TRUCK_UNLOAD           45  // SE_TRACK_HAIKI
#define SE_TRUCK_DOOR             46  // SE_TRACK_DOOR
#define SE_BERRY_BLENDER          47  // SE_MOTER
#define SE_SAVE                   48  // SE_SAVE
#define SE_BALL_BOUNCE_1          49  // SE_KON
#define SE_BALL_BOUNCE_2          50  // SE_KON2
#define SE_BALL_BOUNCE_3          51  // SE_KON3
#define SE_BALL_BOUNCE_4          52  // SE_KON4
#define SE_BALL_TRADE             53  // SE_SUIKOMU
#define SE_BALL_THROW             54  // SE_NAGERU
#define SE_NOTE_C                 55  // SE_TOY_C
#define SE_NOTE_D                 56  // SE_TOY_D
#define SE_NOTE_E                 57  // SE_TOY_E
#define SE_NOTE_F                 58  // SE_TOY_F
#define SE_NOTE_G                 59  // SE_TOY_G
#define SE_NOTE_A                 60  // SE_TOY_A
#define SE_NOTE_B                 61  // SE_TOY_B
#define SE_NOTE_C_HIGH            62  // SE_TOY_C1
#define SE_PUDDLE                 63  // SE_MIZU
#define SE_BRIDGE_WALK            64  // SE_HASHI
#define SE_ITEMFINDER             65  // SE_DAUGI
#define SE_DING_DONG              66  // SE_PINPON
#define SE_BALLOON_RED            67  // SE_FUUSEN1
#define SE_BALLOON_BLUE           68  // SE_FUUSEN2
#define SE_BALLOON_YELLOW         69  // SE_FUUSEN3
#define SE_BREAKABLE_DOOR         70  // SE_TOY_KABE
#define SE_MUD_BALL               71  // SE_TOY_DANGO
#define SE_FIELD_POISON           72  // SE_DOKU
#define SE_ESCALATOR              73  // SE_ESUKA
#define SE_THUNDERSTORM           74  // SE_T_AME
#define SE_THUNDERSTORM_STOP      75  // SE_T_AME_E
#define SE_DOWNPOUR               76  // SE_T_OOAME
#define SE_DOWNPOUR_STOP          77  // SE_T_OOAME_E
#define SE_RAIN                   78  // SE_T_KOAME
#define SE_RAIN_STOP              79  // SE_T_KOAME_E
#define SE_THUNDER                80  // SE_T_KAMI
#define SE_THUNDER2               81  // SE_T_KAMI2
#define SE_ELEVATOR               82  // SE_ELEBETA
#define SE_LOW_HEALTH             83  // SE_HINSI
#define SE_EXP_MAX                84  // SE_EXPMAX
#define SE_ROULETTE_BALL          85  // SE_TAMAKORO
#define SE_ROULETTE_BALL2         86  // SE_TAMAKORO_E
#define SE_TAILLOW_WING_FLAP      87  // SE_BASABASA
#define SE_RS_SHOP                88  // SE_REGI
#define SE_CONTEST_HEART          89  // SE_C_GAJI
#define SE_CONTEST_CURTAIN_RISE   90  // SE_C_MAKU_U
#define SE_CONTEST_CURTAIN_FALL   91  // SE_C_MAKU_D
#define SE_CONTEST_ICON_CHANGE    92  // SE_C_PASI
#define SE_CONTEST_ICON_CLEAR     93  // SE_C_SYU
#define SE_CONTEST_MONS_TURN      94  // SE_C_PIKON
#define SE_SHINY                  95  // SE_REAPOKE
#define SE_INTRO_BLAST            96  // SE_OP_BASYU
#define SE_MUGSHOT                97  // SE_BT_START
#define SE_APPLAUSE               98  // SE_DENDOU
#define SE_VEND                   99  // SE_JIHANKI
#define SE_ORB                    100 // SE_TAMA
#define SE_DEX_SCROLL             101 // SE_Z_SCROLL
#define SE_DEX_PAGE               102 // SE_Z_PAGE
#define SE_POKENAV_ON             103 // SE_PN_ON
#define SE_POKENAV_OFF            104 // SE_PN_OFF
#define SE_DEX_SEARCH             105 // SE_Z_SEARCH
#define SE_EGG_HATCH              106 // SE_TAMAGO
#define SE_BALL_TRAY_ENTER        107 // SE_TB_START
#define SE_BALL_TRAY_BALL         108 // SE_TB_KON
#define SE_BALL_TRAY_EXIT         109 // SE_TB_KARA
#define SE_GLASS_FLUTE            110 // SE_BIDORO
// Move SFX
#define SE_M_THUNDERBOLT          111 // SE_W085
#define SE_M_THUNDERBOLT2         112 // SE_W085B
#define SE_M_HARDEN               113 // SE_W231
#define SE_M_NIGHTMARE            114 // SE_W171
#define SE_M_VITAL_THROW          115 // SE_W233
#define SE_M_VITAL_THROW2         116 // SE_W233B
#define SE_M_BUBBLE               117 // SE_W145
#define SE_M_BUBBLE2              118 // SE_W145B
#define SE_M_BUBBLE3              119 // SE_W145C
#define SE_M_RAIN_DANCE           120 // SE_W240
#define SE_M_CUT                  121 // SE_W015
#define SE_M_STRING_SHOT          122 // SE_W081
#define SE_M_STRING_SHOT2         123 // SE_W081B
#define SE_M_ROCK_THROW           124 // SE_W088
#define SE_M_GUST                 125 // SE_W016
#define SE_M_GUST2                126 // SE_W016B
#define SE_M_DOUBLE_SLAP          127 // SE_W003
#define SE_M_DOUBLE_TEAM          128 // SE_W104
#define SE_M_RAZOR_WIND           129 // SE_W013
#define SE_M_ICY_WIND             130 // SE_W196
#define SE_M_THUNDER_WAVE         131 // SE_W086
#define SE_M_COMET_PUNCH          132 // SE_W004
#define SE_M_MEGA_KICK            133 // SE_W025
#define SE_M_MEGA_KICK2           134 // SE_W025B
#define SE_M_CRABHAMMER           135 // SE_W152
#define SE_M_JUMP_KICK            136 // SE_W026
#define SE_M_FLAME_WHEEL          137 // SE_W172
#define SE_M_FLAME_WHEEL2         138 // SE_W172B
#define SE_M_FLAMETHROWER         139 // SE_W053
#define SE_M_FIRE_PUNCH           140 // SE_W007
#define SE_M_TOXIC                141 // SE_W092
#define SE_M_SACRED_FIRE          142 // SE_W221
#define SE_M_SACRED_FIRE2         143 // SE_W221B
#define SE_M_EMBER                144 // SE_W052
#define SE_M_TAKE_DOWN            145 // SE_W036
#define SE_M_BLIZZARD             146 // SE_W059
#define SE_M_BLIZZARD2            147 // SE_W059B
#define SE_M_SCRATCH              148 // SE_W010
#define SE_M_VICEGRIP             149 // SE_W011
#define SE_M_WING_ATTACK          150 // SE_W017
#define SE_M_FLY                  151 // SE_W019
#define SE_M_SAND_ATTACK          152 // SE_W028
#define SE_M_RAZOR_WIND2          153 // SE_W013B
#define SE_M_BITE                 154 // SE_W044
#define SE_M_HEADBUTT             155 // SE_W029
#define SE_M_SURF                 156 // SE_W057
#define SE_M_HYDRO_PUMP           157 // SE_W056
#define SE_M_WHIRLPOOL            158 // SE_W250
#define SE_M_HORN_ATTACK          159 // SE_W030
#define SE_M_TAIL_WHIP            160 // SE_W039
#define SE_M_MIST                 161 // SE_W054
#define SE_M_POISON_POWDER        162 // SE_W077
#define SE_M_BIND                 163 // SE_W020
#define SE_M_DRAGON_RAGE          164 // SE_W082
#define SE_M_SING                 165 // SE_W047
#define SE_M_PERISH_SONG          166 // SE_W195
#define SE_M_PAY_DAY              167 // SE_W006
#define SE_M_DIG                  168 // SE_W091
#define SE_M_DIZZY_PUNCH          169 // SE_W146
#define SE_M_SELF_DESTRUCT        170 // SE_W120
#define SE_M_EXPLOSION            171 // SE_W153
#define SE_M_ABSORB_2             172 // SE_W071B
#define SE_M_ABSORB               173 // SE_W071
#define SE_M_SCREECH              174 // SE_W103
#define SE_M_BUBBLE_BEAM          175 // SE_W062
#define SE_M_BUBBLE_BEAM2         176 // SE_W062B
#define SE_M_SUPERSONIC           177 // SE_W048
#define SE_M_BELLY_DRUM           178 // SE_W187
#define SE_M_METRONOME            179 // SE_W118
#define SE_M_BONEMERANG           180 // SE_W155
#define SE_M_LICK                 181 // SE_W122
#define SE_M_PSYBEAM              182 // SE_W060
#define SE_M_FAINT_ATTACK         183 // SE_W185
#define SE_M_SWORDS_DANCE         184 // SE_W014
#define SE_M_LEER                 185 // SE_W043
#define SE_M_SWAGGER              186 // SE_W207
#define SE_M_SWAGGER2             187 // SE_W207B
#define SE_M_HEAL_BELL            188 // SE_W215
#define SE_M_CONFUSE_RAY          189 // SE_W109
#define SE_M_SNORE                190 // SE_W173
#define SE_M_BRICK_BREAK          191 // SE_W280
#define SE_M_GIGA_DRAIN           192 // SE_W202
#define SE_M_PSYBEAM2             193 // SE_W060B
#define SE_M_SOLARBEAM           194 // SE_W076
#define SE_M_PETAL_DANCE          195 // SE_W080
#define SE_M_TELEPORT             196 // SE_W100
#define SE_M_MINIMIZE             197 // SE_W107
#define SE_M_SKETCH               198 // SE_W166
#define SE_M_SWIFT                199 // SE_W129
#define SE_M_REFLECT              200 // SE_W115
#define SE_M_BARRIER              201 // SE_W112
#define SE_M_DETECT               202 // SE_W197
#define SE_M_LOCK_ON              203 // SE_W199
#define SE_M_MOONLIGHT            204 // SE_W236
#define SE_M_CHARM                205 // SE_W204
#define SE_M_CHARGE               206 // SE_W268
#define SE_M_STRENGTH             207 // SE_W070
#define SE_M_HYPER_BEAM           208 // SE_W063
#define SE_M_WATERFALL            209 // SE_W127
#define SE_M_REVERSAL             210 // SE_W179
#define SE_M_ACID_ARMOR           211 // SE_W151
#define SE_M_SANDSTORM            212 // SE_W201
#define SE_M_TRI_ATTACK           213 // SE_W161
#define SE_M_TRI_ATTACK2          214 // SE_W161B
#define SE_M_ENCORE               215 // SE_W227
#define SE_M_ENCORE2              216 // SE_W227B
#define SE_M_BATON_PASS           217 // SE_W226
#define SE_M_MILK_DRINK           218 // SE_W208
#define SE_M_ATTRACT              219 // SE_W213
#define SE_M_ATTRACT2             220 // SE_W213B
#define SE_M_MORNING_SUN          221 // SE_W234
#define SE_M_FLATTER              222 // SE_W260
#define SE_M_SAND_TOMB            223 // SE_W328
#define SE_M_GRASSWHISTLE         224 // SE_W320
#define SE_M_SPIT_UP              225 // SE_W255
#define SE_M_DIVE                 226 // SE_W291
#define SE_M_EARTHQUAKE           227 // SE_W089
#define SE_M_TWISTER              228 // SE_W239
#define SE_M_SWEET_SCENT          229 // SE_W230
#define SE_M_YAWN                 230 // SE_W281
#define SE_M_SKY_UPPERCUT         231 // SE_W327
#define SE_M_STAT_INCREASE        232 // SE_W287
#define SE_M_HEAT_WAVE            233 // SE_W257
#define SE_M_UPROAR               234 // SE_W253
#define SE_M_HAIL                 235 // SE_W258
#define SE_M_COSMIC_POWER         236 // SE_W322
#define SE_M_TEETER_DANCE         237 // SE_W298
#define SE_M_STAT_DECREASE        238 // SE_W287B
#define SE_M_HAZE                 239 // SE_W114
#define SE_M_HYPER_BEAM2          240 // SE_W063B
// New FRLG SFX
#define SE_DOOR                   241 // SE_RG_W_DOOR
#define SE_CARD_FLIP              242 // SE_RG_CARD1
#define SE_CARD_FLIPPING          243 // SE_RG_CARD2
#define SE_CARD_OPEN              244 // SE_RG_CARD3
#define SE_BAG_CURSOR             245 // SE_RG_BAG1
#define SE_BAG_POCKET             246 // SE_RG_BAG2
#define SE_BALL_CLICK             247 // SE_RG_GETTING
#define SE_SHOP                   248 // SE_RG_SHOP
#define SE_SS_ANNE_HORN           249 // SE_RG_KITEKI
#define SE_HELP_OPEN              250 // SE_RG_HELP_OP
#define SE_HELP_CLOSE             251 // SE_RG_HELP_CL
#define SE_HELP_ERROR             252 // SE_RG_HELP_NG
#define SE_DEOXYS_MOVE            253 // SE_RG_DEOMOV
#define SE_POKE_JUMP_SUCCESS      254 // SE_RG_EXCELLENT
#define SE_POKE_JUMP_FAILURE      255 // SE_RG_NAWAMISS
// Music kept from RS
#define MUS_HEAL                  256 // MUS_ME_ASA
#define MUS_LEVEL_UP              257 // MUS_FANFA1
#define MUS_OBTAIN_ITEM           258 // MUS_FANFA4
#define MUS_EVOLVED               259 // MUS_FANFA5
#define MUS_OBTAIN_BADGE          260 // MUS_ME_BACHI
#define MUS_OBTAIN_TMHM           261 // MUS_ME_WAZA
#define MUS_OBTAIN_BERRY          262 // MUS_ME_KINOMI
#define MUS_EVOLUTION_INTRO       263 // MUS_ME_SHINKA
#define MUS_EVOLUTION             264 // MUS_SHINKA
#define MUS_RS_VS_GYM_LEADER      265 // MUS_BATTLE32
#define MUS_RS_VS_TRAINER         266 // MUS_BATTLE20
#define MUS_SCHOOL                267 // MUS_P_SCHOOL
#define MUS_SLOTS_JACKPOT         268 // MUS_ME_B_BIG
#define MUS_SLOTS_WIN             269 // MUS_ME_B_SMALL
#define MUS_MOVE_DELETED          270 // MUS_ME_WASURE
#define MUS_TOO_BAD               271 // MUS_ME_ZANNEN
// New FRLG Music
#define MUS_FOLLOW_ME             272 // MUS_RG_ANNAI
#define MUS_GAME_CORNER           273 // MUS_RG_SLOT
#define MUS_ROCKET_HIDEOUT        274 // MUS_RG_AJITO
#define MUS_GYM                   275 // MUS_RG_GYM
#define MUS_JIGGLYPUFF            276 // MUS_RG_PURIN
#define MUS_INTRO_FIGHT           277 // MUS_RG_DEMO
#define MUS_TITLE                 278 // MUS_RG_TITLE
#define MUS_CINNABAR              279 // MUS_RG_GUREN
#define MUS_LAVENDER              280 // MUS_RG_SHION
#define MUS_HEAL_UNUSED           281 // MUS_RG_KAIHUKU
#define MUS_CYCLING               282 // MUS_RG_CYCLING
#define MUS_ENCOUNTER_ROCKET      283 // MUS_RG_ROCKET
#define MUS_ENCOUNTER_GIRL        284 // MUS_RG_SHOUJO
#define MUS_ENCOUNTER_BOY         285 // MUS_RG_SHOUNEN
#define MUS_HALL_OF_FAME          286 // MUS_RG_DENDOU
#define MUS_VIRIDIAN_FOREST       287 // MUS_RG_T_MORI
#define MUS_MT_MOON               288 // MUS_RG_OTSUKIMI
#define MUS_POKE_MANSION          289 // MUS_RG_POKEYASHI
#define MUS_CREDITS               290 // MUS_RG_ENDING
#define MUS_ROUTE1                291 // MUS_RG_LOAD01
#define MUS_ROUTE24               292 // MUS_RG_OPENING
#define MUS_ROUTE3                293 // MUS_RG_LOAD02
#define MUS_ROUTE11               294 // MUS_RG_LOAD03
#define MUS_VICTORY_ROAD          295 // MUS_RG_CHAMP_R
#define MUS_VS_GYM_LEADER         296 // MUS_RG_VS_GYM
#define MUS_VS_TRAINER            297 // MUS_RG_VS_TORE
#define MUS_VS_WILD               298 // MUS_RG_VS_YASEI
#define MUS_VS_CHAMPION           299 // MUS_RG_VS_LAST
#define MUS_PALLET                300 // MUS_RG_MASARA
#define MUS_OAK_LAB               301 // MUS_RG_KENKYU
#define MUS_OAK                   302 // MUS_RG_OHKIDO
#define MUS_POKE_CENTER           303 // MUS_RG_POKECEN
#define MUS_SS_ANNE               304 // MUS_RG_SANTOAN
#define MUS_SURF                  305 // MUS_RG_NAMINORI
#define MUS_POKE_TOWER            306 // MUS_RG_P_TOWER
#define MUS_SILPH                 307 // MUS_RG_SHIRUHU
#define MUS_FUCHSIA               308 // MUS_RG_HANADA
#define MUS_CELADON               309 // MUS_RG_TAMAMUSI
#define MUS_VICTORY_TRAINER       310 // MUS_RG_WIN_TRE
#define MUS_VICTORY_WILD          311 // MUS_RG_WIN_YASEI
#define MUS_VICTORY_GYM_LEADER    312 // MUS_RG_WIN_GYM
#define MUS_VERMILLION            313 // MUS_RG_KUCHIBA
#define MUS_PEWTER                314 // MUS_RG_NIBI
#define MUS_ENCOUNTER_RIVAL       315 // MUS_RG_RIVAL1
#define MUS_RIVAL_EXIT            316 // MUS_RG_RIVAL2
#define MUS_DEX_RATING            317 // MUS_RG_FAN2
#define MUS_OBTAIN_KEY_ITEM       318 // MUS_RG_FAN5
#define MUS_CAUGHT_INTRO          319 // MUS_RG_FAN6
#define MUS_PHOTO                 320 // MUS_ME_RG_PHOTO
#define MUS_GAME_FREAK            321 // MUS_RG_TITLEROG
#define MUS_CAUGHT                322 // MUS_RG_GET_YASEI
#define MUS_NEW_GAME_INSTRUCT     323 // MUS_RG_SOUSA
#define MUS_NEW_GAME_INTRO        324 // MUS_RG_SEKAIKAN
#define MUS_NEW_GAME_EXIT         325 // MUS_RG_SEIBETU
#define MUS_POKE_JUMP             326 // MUS_RG_JUMP
#define MUS_UNION_ROOM            327 // MUS_RG_UNION
#define MUS_NET_CENTER            328 // MUS_RG_NETWORK
#define MUS_MYSTERY_GIFT          329 // MUS_RG_OKURIMONO
#define MUS_BERRY_PICK            330 // MUS_RG_KINOMIKUI
#define MUS_SEVII_CAVE            331 // MUS_RG_NANADUNGEON
#define MUS_TEACHY_TV_SHOW        332 // MUS_RG_OSHIE_TV
#define MUS_SEVII_ROUTE           333 // MUS_RG_NANASHIMA
#define MUS_SEVII_DUNGEON         334 // MUS_RG_NANAISEKI
#define MUS_SEVII_123             335 // MUS_RG_NANA123
#define MUS_SEVII_45              336 // MUS_RG_NANA45
#define MUS_SEVII_67              337 // MUS_RG_NANA67
#define MUS_POKE_FLUTE            338 // MUS_RG_POKEFUE
#define MUS_VS_DEOXYS             339 // MUS_RG_VS_DEO
#define MUS_VS_MEWTWO             340 // MUS_RG_VS_MYU2
#define MUS_VS_LEGEND             341 // MUS_RG_VS_DEN
#define MUS_ENCOUNTER_GYM_LEADER  342 // MUS_RG_EXEYE
#define MUS_ENCOUNTER_DEOXYS      343 // MUS_RG_DEOEYE
#define MUS_TRAINER_TOWER         344 // MUS_RG_T_TOWER
#define MUS_SLOW_PALLET           345 // MUS_RG_SLOWMASARA
#define MUS_TEACHY_TV_MENU        346 // MUS_RG_TVNOIZE
// RSE
#define MUS_RSE_LITTLEROOT_TEST 350
#define MUS_RSE_GSC_ROUTE38 351
#define MUS_RSE_CAUGHT 352
#define MUS_RSE_VICTORY_WILD 353
#define MUS_RSE_VICTORY_GYM_LEADER 354
#define MUS_RSE_VICTORY_LEAGUE 355
#define MUS_RSE_C_COMM_CENTER 356
#define MUS_RSE_GSC_PEWTER 357
#define MUS_RSE_C_VS_LEGEND_BEAST 358
#define MUS_RSE_ROUTE101 359
#define MUS_RSE_ROUTE110 360
#define MUS_RSE_ROUTE120 361
#define MUS_RSE_PETALBURG 362
#define MUS_RSE_OLDALE 363
#define MUS_RSE_GYM 364
#define MUS_RSE_SURF 365
#define MUS_RSE_PETALBURG_WOODS 366
#define MUS_RSE_LEVEL_UP 367
#define MUS_RSE_HEAL 368
#define MUS_RSE_OBTAIN_BADGE 369
#define MUS_RSE_OBTAIN_ITEM 370
#define MUS_RSE_EVOLVED 371
#define MUS_RSE_OBTAIN_TMHM 372
#define MUS_RSE_LILYCOVE_MUSEUM 373
#define MUS_RSE_ROUTE122 374
#define MUS_RSE_OCEANIC_MUSEUM 375
#define MUS_RSE_EVOLUTION_INTRO 376
#define MUS_RSE_EVOLUTION 377
#define MUS_RSE_MOVE_DELETED 378
#define MUS_RSE_ENCOUNTER_GIRL 379
#define MUS_RSE_ENCOUNTER_MALE 380
#define MUS_RSE_ABANDONED_SHIP 381
#define MUS_RSE_FORTREE 382
#define MUS_RSE_BIRCH_LAB 383
#define MUS_RSE_B_TOWER_RS 384
#define MUS_RSE_ENCOUNTER_SWIMMER 385
#define MUS_RSE_CAVE_OF_ORIGIN 386
#define MUS_RSE_OBTAIN_BERRY 387
#define MUS_RSE_AWAKEN_LEGEND 388
#define MUS_RSE_SLOTS_JACKPOT 389
#define MUS_RSE_SLOTS_WIN 390
#define MUS_RSE_TOO_BAD 391
#define MUS_RSE_ROULETTE 392
#define MUS_RSE_LINK_CONTEST_P1 393
#define MUS_RSE_LINK_CONTEST_P2 394
#define MUS_RSE_LINK_CONTEST_P3 395
#define MUS_RSE_LINK_CONTEST_P4 396
#define MUS_RSE_ENCOUNTER_RICH 397
#define MUS_RSE_VERDANTURF 398
#define MUS_RSE_RUSTBORO 399
#define MUS_RSE_POKE_CENTER 400
#define MUS_RSE_ROUTE104 401
#define MUS_RSE_ROUTE119 402
#define MUS_RSE_CYCLING 403
#define MUS_RSE_POKE_MART 404
#define MUS_RSE_LITTLEROOT 405
#define MUS_RSE_MT_CHIMNEY 406
#define MUS_RSE_ENCOUNTER_FEMALE 407
#define MUS_RSE_LILYCOVE 408
#define MUS_RSE_ROUTE111 409
#define MUS_RSE_HELP 410
#define MUS_RSE_UNDERWATER 411
#define MUS_RSE_VICTORY_TRAINER 412
#define MUS_RSE_TITLE 413
#define MUS_RSE_INTRO 414
#define MUS_RSE_ENCOUNTER_MAY 415
#define MUS_RSE_ENCOUNTER_INTENSE 416
#define MUS_RSE_ENCOUNTER_COOL 417
#define MUS_RSE_ROUTE113 418
#define MUS_RSE_ENCOUNTER_AQUA 419
#define MUS_RSE_FOLLOW_ME 420
#define MUS_RSE_ENCOUNTER_BRENDAN 421
#define MUS_RSE_EVER_GRANDE 422
#define MUS_RSE_ENCOUNTER_SUSPICIOUS 423
#define MUS_RSE_VICTORY_AQUA_MAGMA 424
#define MUS_RSE_CABLE_CAR 425
#define MUS_RSE_GAME_CORNER 426
#define MUS_RSE_DEWFORD 427
#define MUS_RSE_SAFARI_ZONE 428
#define MUS_RSE_VICTORY_ROAD 429
#define MUS_RSE_AQUA_MAGMA_HIDEOUT 430
#define MUS_RSE_SAILING 431
#define MUS_RSE_MT_PYRE 432
#define MUS_RSE_SLATEPORT 433
#define MUS_RSE_MT_PYRE_EXTERIOR 434
#define MUS_RSE_SCHOOL 435
#define MUS_RSE_HALL_OF_FAME 436
#define MUS_RSE_FALLARBOR 437
#define MUS_RSE_SEALED_CHAMBER 438
#define MUS_RSE_CONTEST_WINNER 439
#define MUS_RSE_CONTEST 440
#define MUS_RSE_ENCOUNTER_MAGMA 441
#define MUS_RSE_INTRO_BATTLE 442
#define MUS_RSE_ABNORMAL_WEATHER 443
#define MUS_RSE_WEATHER_GROUDON 444
#define MUS_RSE_SOOTOPOLIS 445
#define MUS_RSE_CONTEST_RESULTS 446
#define MUS_RSE_HALL_OF_FAME_ROOM 447
#define MUS_RSE_TRICK_HOUSE 448
#define MUS_RSE_ENCOUNTER_TWINS 449
#define MUS_RSE_ENCOUNTER_ELITE_FOUR 450
#define MUS_RSE_ENCOUNTER_HIKER 451
#define MUS_RSE_CONTEST_LOBBY 452
#define MUS_RSE_ENCOUNTER_INTERVIEWER 453
#define MUS_RSE_ENCOUNTER_CHAMPION 454
#define MUS_RSE_CREDITS 455
#define MUS_RSE_END 456
#define MUS_RSE_B_FRONTIER 457
#define MUS_RSE_B_ARENA 458
#define MUS_RSE_OBTAIN_B_POINTS 459
#define MUS_RSE_REGISTER_MATCH_CALL 460
#define MUS_RSE_B_PYRAMID 461
#define MUS_RSE_B_PYRAMID_TOP 462
#define MUS_RSE_B_PALACE 463
#define MUS_RSE_RAYQUAZA_APPEARS 464
#define MUS_RSE_B_TOWER 465
#define MUS_RSE_OBTAIN_SYMBOL 466
#define MUS_RSE_B_DOME 467
#define MUS_RSE_B_PIKE 468
#define MUS_RSE_B_FACTORY 469
#define MUS_RSE_VS_RAYQUAZA 470
#define MUS_RSE_VS_FRONTIER_BRAIN 471
#define MUS_RSE_VS_MEW 472
#define MUS_RSE_B_DOME_LOBBY 473
#define MUS_RSE_VS_WILD 474
#define MUS_RSE_VS_AQUA_MAGMA 475
#define MUS_RSE_VS_TRAINER 476
#define MUS_RSE_VS_GYM_LEADER 477
#define MUS_RSE_VS_CHAMPION 478
#define MUS_RSE_VS_REGI 479
#define MUS_RSE_VS_KYOGRE_GROUDON 480
#define MUS_RSE_VS_RIVAL 481
#define MUS_RSE_VS_ELITE_FOUR 482
#define MUS_RSE_VS_AQUA_MAGMA_LEADER 483

#define PH_TRAP_BLEND 559
#define PH_TRAP_HELD 560
#define PH_TRAP_SOLO 561
#define PH_FACE_BLEND 562
#define PH_FACE_HELD 563
#define PH_FACE_SOLO 564
#define PH_CLOTH_BLEND 565
#define PH_CLOTH_HELD 566
#define PH_CLOTH_SOLO 567
#define PH_DRESS_BLEND 568
#define PH_DRESS_HELD 569
#define PH_DRESS_SOLO 570
#define PH_FLEECE_BLEND 571
#define PH_FLEECE_HELD 572
#define PH_FLEECE_SOLO 573
#define PH_KIT_BLEND 574
#define PH_KIT_HELD 575
#define PH_KIT_SOLO 576
#define PH_PRICE_BLEND 577
#define PH_PRICE_HELD 578
#define PH_PRICE_SOLO 579
#define PH_LOT_BLEND 580
#define PH_LOT_HELD 581
#define PH_LOT_SOLO 582
#define PH_GOAT_BLEND 583
#define PH_GOAT_HELD 584
#define PH_GOAT_SOLO 585
#define PH_THOUGHT_BLEND 586
#define PH_THOUGHT_HELD 587
#define PH_THOUGHT_SOLO 588
#define PH_CHOICE_BLEND 589
#define PH_CHOICE_HELD 590
#define PH_CHOICE_SOLO 591
#define PH_MOUTH_BLEND 592
#define PH_MOUTH_HELD 593
#define PH_MOUTH_SOLO 594
#define PH_FOOT_BLEND 595
#define PH_FOOT_HELD 596
#define PH_FOOT_SOLO 597
#define PH_GOOSE_BLEND 598
#define PH_GOOSE_HELD 599
#define PH_GOOSE_SOLO 600
#define PH_STRUT_BLEND 601
#define PH_STRUT_HELD 602
#define PH_STRUT_SOLO 603
#define PH_CURE_BLEND 604
#define PH_CURE_HELD 605
#define PH_CURE_SOLO 606
#define PH_NURSE_BLEND 607
#define PH_NURSE_HELD 608
#define PH_NURSE_SOLO 609
// DP
#define MUS_DP_INTRO 610
#define MUS_DP_TITLE 611
#define MUS_DP_ROWAN 612
#define MUS_DP_TV_BROADCAST 613
#define MUS_DP_TV_END 614
#define MUS_DP_TWINLEAF_DAY 615
#define MUS_DP_TWINLEAF_NIGHT 616
#define MUS_DP_RIVAL 617
#define MUS_DP_ROUTE201_DAY 618
#define MUS_DP_ROUTE201_NIGHT 619
#define MUS_DP_LAKE 620
#define MUS_DP_LAKE_EVENT 621
#define MUS_DP_VS_WILD 622
#define MUS_DP_VICTORY_WILD 623
#define MUS_DP_DAWN 624
#define MUS_DP_LUCAS 625
#define MUS_DP_OBTAIN_ITEM 626
#define MUS_DP_SANDGEM_DAY 627
#define MUS_DP_SANDGEM_NIGHT 628
#define MUS_DP_ROWAN_LAB 629
#define MUS_DP_FOLLOW_ME 630
#define MUS_DP_POKE_CENTER_DAY 631
#define MUS_DP_POKE_CENTER_NIGHT 632
#define MUS_DP_HEAL 633
#define MUS_DP_ENCOUNTER_BOY 634
#define MUS_DP_ENCOUNTER_GIRL 635
#define MUS_DP_VS_TRAINER 636
#define MUS_DP_VICTORY_TRAINER 637
#define MUS_DP_JUBILIFE_DAY 638
#define MUS_DP_JUBILIFE_NIGHT 639
#define MUS_DP_OBTAIN_KEY_ITEM 640
#define MUS_DP_POKE_MART 641
#define MUS_DP_ROUTE203_DAY 642
#define MUS_DP_ROUTE203_NIGHT 643
#define MUS_DP_VS_RIVAL 644
#define MUS_DP_OREBURGH_GATE 645
#define MUS_DP_OBTAIN_TMHM 646
#define MUS_DP_OREBURGH_DAY 647
#define MUS_DP_OREBURGH_NIGHT 648
#define MUS_DP_OREBURGH_MINE 649
#define MUS_DP_GYM 650
#define MUS_DP_VS_GYM_LEADER 651
#define MUS_DP_VICTORY_GYM_LEADER 652
#define MUS_DP_OBTAIN_BADGE 653
#define MUS_DP_ENCOUNTER_TWINS 654
#define MUS_DP_LEVEL_UP 655
#define MUS_DP_FLOAROMA_DAY 656
#define MUS_DP_FLOAROMA_NIGHT 657
#define MUS_DP_OBTAIN_BERRY 658
#define MUS_DP_ROUTE205_DAY 659
#define MUS_DP_ROUTE205_NIGHT 660
#define MUS_DP_ENCOUNTER_GALACTIC 661
#define MUS_DP_VS_GALACTIC_GRUNT 662
#define MUS_DP_ETERNA_FOREST 663
#define MUS_DP_LETS_GO_TOGETHER 664
#define MUS_DP_ETERNA_DAY 665
#define MUS_DP_ETERNA_NIGHT 666
#define MUS_DP_GALACTIC_ETERNA_BUILDING 667
#define MUS_DP_VS_GALACTIC_COMMANDER 668
#define MUS_DP_VICTORY_GALACTIC 669
#define MUS_DP_EVOLUTION 670
#define MUS_DP_EVOLVED 671
#define MUS_DP_CYCLING 672
#define MUS_DP_ENCOUNTER_CYCLIST 673
#define MUS_DP_ROUTE206_DAY 674
#define MUS_DP_ROUTE206_NIGHT 675
#define MUS_DP_HEARTHOME_DAY 676
#define MUS_DP_HEARTHOME_NIGHT 677
#define MUS_DP_ROUTE209_DAY 678
#define MUS_DP_ROUTE209_NIGHT 679
#define MUS_DP_ENCOUNTER_HIKER 680
#define MUS_DP_SOLACEON_DAY 681
#define MUS_DP_SOLACEON_NIGHT 682
#define MUS_DP_POKETCH 683
#define MUS_DP_ROUTE210_DAY 684
#define MUS_DP_ROUTE210_NIGHT 685
#define MUS_DP_VEILSTONE_DAY 686
#define MUS_DP_VEILSTONE_NIGHT 687
#define MUS_DP_VALOR_LAKEFRONT_DAY 688
#define MUS_DP_VALOR_LAKEFRONT_NIGHT 689
#define MUS_DP_CANALAVE_DAY 690
#define MUS_DP_CANALAVE_NIGHT 691
#define MUS_DP_ROUTE216_DAY 692
#define MUS_DP_ROUTE216_NIGHT 693
#define MUS_DP_SNOWPOINT_DAY 694
#define MUS_DP_SNOWPOINT_NIGHT 695
#define MUS_DP_GALACTIC_HQ 696
#define MUS_DP_VS_GALACTIC_BOSS 697
#define MUS_DP_GALACTIC_HQ_BASEMENT 698
#define MUS_DP_MT_CORONET 699
#define MUS_DP_SPEAR_PILLAR 700
#define MUS_DP_LEGEND_APPEARS 701
#define MUS_DP_CATASTROPHE 702
#define MUS_DP_VS_DIALGA_PALKIA 703
#define MUS_DP_SUNYSHORE_DAY 704
#define MUS_DP_SUNYSHORE_NIGHT 705
#define MUS_DP_VICTORY_ROAD 706
#define MUS_DP_ENCOUNTER_ACE_TRAINER 707
#define MUS_DP_POKEMON_LEAGUE_DAY 708
#define MUS_DP_POKEMON_LEAGUE_NIGHT 709
#define MUS_DP_FIGHT_AREA_DAY 710
#define MUS_DP_FIGHT_AREA_NIGHT 711
#define MUS_DP_ROUTE225_DAY 712
#define MUS_DP_ROUTE225_NIGHT 713
#define MUS_DP_ROUTE228_DAY 714
#define MUS_DP_ROUTE228_NIGHT 715
#define MUS_DP_WFC 716
#define MUS_DP_TV_STATION 717
#define MUS_DP_GTS 718
#define MUS_DP_SURF 719
#define MUS_DP_MOVE_DELETED 720
#define MUS_DP_ENCOUNTER_INTENSE 721
#define MUS_DP_ENCOUNTER_SAILOR 722
#define MUS_DP_UNDERGROUND 723
#define MUS_DP_FLAG_CAPTURED 724
#define MUS_DP_ENCOUNTER_LADY 725
#define MUS_DP_OLD_CHATEAU 726
#define MUS_DP_GREAT_MARSH 727
#define MUS_DP_ENCOUNTER_SUSPICIOUS 728
#define MUS_DP_GAME_CORNER 729
#define MUS_DP_SLOTS_WIN 730
#define MUS_DP_SLOTS_JACKPOT 731
#define MUS_DP_ENCOUNTER_RICH 732
#define MUS_DP_LAKE_CAVERNS 733
#define MUS_DP_VS_UXIE_MESPRIT_AZELF 734
#define MUS_DP_POKE_RADAR 735
#define MUS_DP_ENCOUNTER_ARTIST 736
#define MUS_DP_AMITY_SQUARE 737
#define MUS_DP_OBTAIN_ACCESSORY 738
#define MUS_DP_CONTEST_LOBBY 739
#define MUS_DP_POFFINS 740
#define MUS_DP_CONTEST 741
#define MUS_DP_CONTEST_DRESS_UP 742
#define MUS_DP_DANCE_EASY 743
#define MUS_DP_DANCE_DIFFICULT 744
#define MUS_DP_CONTEST_RESULTS 745
#define MUS_DP_CONTEST_WINNER 746
#define MUS_DP_B_TOWER 747
#define MUS_DP_STARK_MOUNTAIN 748
#define MUS_DP_VS_LEGEND 749
#define MUS_DP_MYSTERY_GIFT 750
#define MUS_DP_INSIDE_POKEMON_LEAGUE 751
#define MUS_DP_ENCOUNTER_ELITE_FOUR 752
#define MUS_DP_VS_ELITE_FOUR 753
#define MUS_DP_VICTORY_ELITE_FOUR 754
#define MUS_DP_ENCOUNTER_CHAMPION 755
#define MUS_DP_VS_CHAMPION 756
#define MUS_DP_VICTORY_CHAMPION 757
#define MUS_DP_HALL_OF_FAME_ROOM 758
#define MUS_DP_HALL_OF_FAME 759
#define MUS_DP_CREDITS 760
#define MUS_DP_AZURE_FLUTE 761
#define MUS_DP_HALL_OF_ORIGIN 762
#define MUS_DP_VS_ARCEUS 763
// Pt
#define MUS_PL_INTRO 764
#define MUS_PL_TITLE 765
#define MUS_PL_TV_BROADCAST 766
#define MUS_PL_TV_END 767
#define MUS_PL_LOOKER 768
#define MUS_PL_GLOBAL_TERMINAL 769
#define MUS_PL_WIFI_PLAZA 770
#define MUS_PL_WIFI_MINIGAMES 771
#define MUS_PL_WIN_MINIGAME 772
#define MUS_PL_WIFI_PARADE 773
#define MUS_PL_GIRATINA_APPEARS_1 774
#define MUS_PL_GIRATINA_APPEARS_2 775
#define MUS_PL_DISTORTION_WORLD 776
#define MUS_PL_VS_GIRATINA 777
#define MUS_PL_SPIN_TRADE 778
#define MUS_PL_MYSTERY_GIFT 779
#define MUS_PL_CONTEST_CUTE 780
#define MUS_PL_CONTEST_COOL 781
#define MUS_PL_CONTEST_TOUGH 782
#define MUS_PL_CONTEST_BEAUTY 783
#define MUS_PL_CONTEST_SMART 784
#define MUS_PL_TWINLEAF_MUSIC_BOX 785
#define MUS_PL_LILYCOVE_BOSSA_NOVA 786
#define MUS_PL_FIGHT_AREA_DAY 787
#define MUS_PL_B_ARCADE 788
#define MUS_PL_OBTAIN_ARCADE_POINTS 789
#define MUS_PL_B_HALL 790
#define MUS_PL_B_FACTORY 791
#define MUS_PL_B_CASTLE 792
#define MUS_PL_OBTAIN_CASTLE_POINTS 793
#define MUS_PL_OBTAIN_B_POINTS 794
#define MUS_PL_VS_FRONTIER_BRAIN 795
#define MUS_PL_VICTORY_FRONTIER_BRAIN 796
#define MUS_PL_VS_REGI 797
// HGSS
#define MUS_HG_INTRO 798
#define MUS_HG_TITLE 799
#define MUS_HG_NEW_GAME 800
#define MUS_HG_NEW_BARK 801
#define MUS_HG_FOLLOW_ME_1 802
#define MUS_HG_LYRA 803
#define MUS_HG_ETHAN 804
#define MUS_HG_ELM_LAB 805
#define MUS_HG_OBTAIN_KEY_ITEM 806
#define MUS_HG_ROUTE29 807
#define MUS_HG_VS_WILD 808
#define MUS_HG_VICTORY_WILD 809
#define MUS_HG_CAUGHT 810
#define MUS_HG_LEVEL_UP 811
#define MUS_HG_CHERRYGROVE 812
#define MUS_HG_FOLLOW_ME_2 813
#define MUS_HG_POKE_CENTER 814
#define MUS_HG_HEAL 815
#define MUS_HG_ENCOUNTER_BOY_1 816
#define MUS_HG_VS_TRAINER 817
#define MUS_HG_VICTORY_TRAINER 818
#define MUS_HG_ROUTE30 819
#define MUS_HG_DEX_RATING_1 820
#define MUS_HG_VIOLET 821
#define MUS_HG_SPROUT_TOWER 822
#define MUS_HG_ENCOUNTER_SAGE 823
#define MUS_HG_POKE_MART 824
#define MUS_HG_OBTAIN_EGG 825
#define MUS_HG_KIMONO_GIRL 826
#define MUS_HG_UNION_CAVE 827
#define MUS_HG_OBTAIN_ITEM 828
#define MUS_HG_RUINS_OF_ALPH 829
#define MUS_HG_RADIO_UNOWN 830
#define MUS_HG_DEX_RATING_2 831
#define MUS_HG_AZALEA 832
#define MUS_HG_ENCOUNTER_ROCKET 833
#define MUS_HG_VS_ROCKET 834
#define MUS_HG_ROUTE34 835
#define MUS_HG_ENCOUNTER_RIVAL 836
#define MUS_HG_VS_RIVAL 837
#define MUS_HG_EVOLUTION 838
#define MUS_HG_EVOLUTION_NO_INTRO 839
#define MUS_HG_EVOLVED 840
#define MUS_HG_GOLDENROD 841
#define MUS_HG_GYM 842
#define MUS_HG_VS_GYM_LEADER 843
#define MUS_HG_VICTORY_GYM_LEADER 844
#define MUS_HG_OBTAIN_BADGE 845
#define MUS_HG_RADIO_JINGLE 846
#define MUS_HG_RADIO_BUENA 847
#define MUS_HG_OBTAIN_TMHM 848
#define MUS_HG_GAME_CORNER 849
#define MUS_HG_GAME_CORNER_WIN 850
#define MUS_HG_CARD_FLIP 851
#define MUS_HG_CARD_FLIP_GAME_OVER 852
#define MUS_HG_OBTAIN_ACCESSORY 853
#define MUS_HG_GLOBAL_TERMINAL 854
#define MUS_HG_GTS 855
#define MUS_HG_DEX_RATING_3 856
#define MUS_HG_CYCLING 857
#define MUS_HG_ENCOUNTER_GIRL_1 858
#define MUS_HG_POKEGEAR_REGISTERED 859
#define MUS_HG_NATIONAL_PARK 860
#define MUS_HG_OBTAIN_BERRY 861
#define MUS_HG_ECRUTEAK 862
#define MUS_HG_DANCE_THEATER 863
#define MUS_HG_BURNED_TOWER 864
#define MUS_HG_EUSINE 865
#define MUS_HG_RADIO_OAK 866
#define MUS_HG_DEX_RATING_4 867
#define MUS_HG_ROUTE38 868
#define MUS_HG_RADIO_MARCH 869
#define MUS_HG_VS_RAIKOU 870
#define MUS_HG_LIGHTHOUSE 871
#define MUS_HG_SURF 872
#define MUS_HG_CIANWOOD 873
#define MUS_HG_PT_SPECIAL 874
#define MUS_HG_ROUTE42 875
#define MUS_HG_RADIO_ROCKET 876
#define MUS_HG_TEAM_ROCKET_HQ 877
#define MUS_HG_ENCOUNTER_SUSPICIOUS_1 878
#define MUS_HG_RIVAL_EXIT 879
#define MUS_HG_ROCKET_TAKEOVER 880
#define MUS_HG_ICE_PATH 881
#define MUS_HG_MOVE_DELETED 882
#define MUS_HG_DRAGONS_DEN 883
#define MUS_HG_CLAIR 884
#define MUS_HG_VS_ENTEI 885
#define MUS_HG_BELL_TOWER 886
#define MUS_HG_KIMONO_GIRL_DANCE 887
#define MUS_HG_HO_OH_APPEARS 888
#define MUS_HG_VS_HO_OH 889
#define MUS_HG_ROUTE26 890
#define MUS_HG_SS_AQUA 891
#define MUS_HG_VERMILION 892
#define MUS_HG_VS_GYM_LEADER_KANTO 893
#define MUS_HG_LAVENDER 894
#define MUS_HG_ROCK_TUNNEL 895
#define MUS_HG_VS_WILD_KANTO 896
#define MUS_HG_DEX_RATING_5 897
#define MUS_HG_CERULEAN 898
#define MUS_HG_ROUTE24 899
#define MUS_HG_MAGNET_TRAIN 900
#define MUS_HG_RADIO_LULLABY 901
#define MUS_HG_VS_SUICUNE 902
#define MUS_HG_CELADON 903
#define MUS_HG_ROUTE11 904
#define MUS_HG_RADIO_POKE_FLUTE 905
#define MUS_HG_VIRIDIAN_FOREST 906
#define MUS_HG_ENCOUNTER_BOY_2 907
#define MUS_HG_PEWTER 908
#define MUS_HG_ROUTE3 909
#define MUS_HG_ENCOUNTER_SUSPICIOUS_2 910
#define MUS_HG_MT_MOON_SQUARE 911
#define MUS_HG_ROUTE1 912
#define MUS_HG_PALLET 913
#define MUS_HG_OAK 914
#define MUS_HG_DEX_RATING_6 915
#define MUS_HG_ENCOUNTER_GIRL_2 916
#define MUS_HG_VS_TRAINER_KANTO 917
#define MUS_HG_CINNABAR 918
#define MUS_HG_ROUTE47 919
#define MUS_HG_SAFARI_ZONE_GATE 920
#define MUS_HG_SAFARI_ZONE 921
#define MUS_HG_RADIO_VARIETY 922
#define MUS_HG_BUG_CONTEST_PREP 923
#define MUS_HG_BUG_CATCHING_CONTEST 924
#define MUS_HG_BUG_CONTEST_3RD_PLACE 925
#define MUS_HG_BUG_CONTEST_2ND_PLACE 926
#define MUS_HG_BUG_CONTEST_1ST_PLACE 927
#define MUS_HG_POKEATHLON_LOBBY 928
#define MUS_HG_POKEATHLON_READY 929
#define MUS_HG_POKEATHLON_START 930
#define MUS_HG_POKEATHLON_BEFORE 931
#define MUS_HG_POKEATHLON_EVENT 932
#define MUS_HG_POKEATHLON_1ST_PLACE 933
#define MUS_HG_POKEATHLON_FINALS 934
#define MUS_HG_POKEATHLON_RESULTS 935
#define MUS_HG_POKEATHLON_END 936
#define MUS_HG_POKEATHLON_WINNER 937
#define MUS_HG_MYSTERY_GIFT 938
#define MUS_HG_B_TOWER_RECEPTION 939
#define MUS_HG_B_TOWER 940
#define MUS_HG_OBTAIN_B_POINTS 941
#define MUS_HG_B_FACTORY 942
#define MUS_HG_B_HALL 943
#define MUS_HG_B_ARCADE 944
#define MUS_HG_OBTAIN_ARCADE_POINTS 945
#define MUS_HG_B_CASTLE 946
#define MUS_HG_OBTAIN_CASTLE_POINTS 947
#define MUS_HG_VS_FRONTIER_BRAIN 948
#define MUS_HG_VICTORY_FRONTIER_BRAIN 949
#define MUS_HG_RADIO_TRAINER 950
#define MUS_HG_SPIN_TRADE 951
#define MUS_HG_WFC 952
#define MUS_HG_WIFI_PLAZA 953
#define MUS_HG_WIFI_MINIGAMES 954
#define MUS_HG_WIN_MINIGAME 955
#define MUS_HG_WIFI_PARADE 956
#define MUS_HG_RADIO_ROUTE101 957
#define MUS_HG_RADIO_ROUTE201 958
#define MUS_HG_POKEWALKER 959
#define MUS_HG_SPIKY_EARED_PICHU 960
#define MUS_HG_ENCOUNTER_KIMONO_GIRL 961
#define MUS_HG_LUGIA_APPEARS 962
#define MUS_HG_VS_LUGIA 963
#define MUS_HG_VICTORY_ROAD 964
#define MUS_HG_POKEMON_LEAGUE 965
#define MUS_HG_VS_CHAMPION 966
#define MUS_HG_HALL_OF_FAME 967
#define MUS_HG_CREDITS 968
#define MUS_HG_END 969
#define MUS_HG_VS_KYOGRE_GROUDON 970
#define MUS_HG_SINJOU_RUINS 971
#define MUS_HG_VS_ARCEUS 972
#define MUS_HG_LETS_GO_TOGETHER 973
// BW
#define MUS_BW_GAME_FREAK 974
#define MUS_BW_INTRO 975
#define MUS_BW_THE_POKEMON 976
#define MUS_BW_TITLE 977
#define MUS_BW_NEW_GAME_1 978
#define MUS_BW_NEW_GAME_2 979
#define MUS_BW_BEGINNING 980
#define MUS_BW_NUVEMA 981
#define MUS_BW_VS_RIVAL 982
#define MUS_BW_FOLLOW_ME_1 983
#define MUS_BW_JUNIPER_1 984
#define MUS_BW_JUNIPER_LAB 985
#define MUS_BW_OBTAIN_KEY_ITEM 986
#define MUS_BW_FRIEND 987
#define MUS_BW_ROUTE1 988
#define MUS_BW_VS_WILD 989
#define MUS_BW_VICTORY_WILD 990
#define MUS_BW_LEVEL_UP 991
#define MUS_BW_ACCUMULA 992
#define MUS_BW_FOLLOW_ME_2 993
#define MUS_BW_POKE_CENTER 994
#define MUS_BW_HEAL 995
#define MUS_BW_DEX_RATING_1 996
#define MUS_BW_SAGE 997
#define MUS_BW_ROUTE2_SPRING 998
#define MUS_BW_ROUTE2_SUMMER 999
#define MUS_BW_ROUTE2_AUTUMN 1000
#define MUS_BW_ROUTE2_WINTER 1001
#define MUS_BW_XTRAN_CALL 1002
#define MUS_BW_ENCOUNTER_YOUNGSTER 1003
#define MUS_BW_VS_TRAINER 1004
#define MUS_BW_VICTORY_TRAINER 1005
#define MUS_BW_ENCOUNTER_LASS 1006
#define MUS_BW_OBTAIN_ITEM 1007
#define MUS_BW_STRIATON 1008
#define MUS_BW_DEX_RATING_2 1009
#define MUS_BW_DREAMYARD 1010
#define MUS_BW_DREAMYARD_B1F 1011
#define MUS_BW_PLASMA 1012
#define MUS_BW_VS_PLASMA 1013
#define MUS_BW_VICTORY_PLASMA 1014
#define MUS_BW_EVOLUTION 1015
#define MUS_BW_EVOLUTION_NO_INTRO 1016
#define MUS_BW_EVOLVED 1017
#define MUS_BW_ENCOUNTER_TWINS 1018
#define MUS_BW_CHEREN 1019
#define MUS_BW_TROUBLE 1020
#define MUS_BW_NACRENE 1021
#define MUS_BW_DEX_RATING_3 1022
#define MUS_BW_GYM 1023
#define MUS_BW_VS_GYM_LEADER 1024
#define MUS_BW_VS_WINNING 1025
#define MUS_BW_VICTORY_GYM_LEADER 1026
#define MUS_BW_OBTAIN_BADGE 1027
#define MUS_BW_OBTAIN_TMHM 1028
#define MUS_BW_GATE 1029
#define MUS_BW_SKYARROW_BRIDGE 1030
#define MUS_BW_CASTELIA 1031
#define MUS_BW_ENCOUNTER_CLERK 1032
#define MUS_BW_ROUTE4_SPRING 1033
#define MUS_BW_ROUTE4_SUMMER 1034
#define MUS_BW_ROUTE4_AUTUMN 1035
#define MUS_BW_ROUTE4_WINTER 1036
#define MUS_BW_ENCOUNTER_BACKPACKER 1037
#define MUS_BW_NIMBASA 1038
#define MUS_BW_BIANCA 1039
#define MUS_BW_EMOTION 1040
#define MUS_BW_N 1041
#define MUS_BW_VS_N_1 1042
#define MUS_BW_VS_IN_PINCH 1043
#define MUS_BW_CYCLING 1044
#define MUS_BW_ALDER 1045
#define MUS_BW_DRAWBRIDGE 1046
#define MUS_BW_DRIFTVEIL 1047
#define MUS_BW_COLD_STORAGE 1048
#define MUS_BW_ROUTE6_SPRING 1049
#define MUS_BW_ROUTE6_SUMMER 1050
#define MUS_BW_ROUTE6_AUTUMN 1051
#define MUS_BW_ROUTE6_WINTER 1052
#define MUS_BW_ENCOUNTER_PARASOL 1053
#define MUS_BW_ENCOUNTER_SCIENTIST 1054
#define MUS_BW_CHARGESTONE_CAVE 1055
#define MUS_BW_CHARGESTONE_CAVE_B1F 1056
#define MUS_BW_CHARGESTONE_CAVE_B2F 1057
#define MUS_BW_MISTRALTON 1058
#define MUS_BW_JUNIPER_2 1059
#define MUS_BW_DEX_RATING_4 1060
#define MUS_BW_MOVE_DELETED 1061
#define MUS_BW_ENCOUNTER_PSYCHIC 1062
#define MUS_BW_ICIRRUS 1063
#define MUS_BW_DRAGONSPIRAL_TOWER 1064
#define MUS_BW_ENCOUNTER_PLASMA 1065
#define MUS_BW_DRAGONSPIRAL_TOWER_TOP 1066
#define MUS_BW_RELIC_CASTLE 1067
#define MUS_BW_OBTAIN_STONE 1068
#define MUS_BW_TUBELINE_BRIDGE 1069
#define MUS_BW_POKE_MART 1070
#define MUS_BW_ENCOUNTER_ROUGHNECK 1071
#define MUS_BW_OPELUCID_BLACK 1072
#define MUS_BW_OPELUCID_WHITE 1073
#define MUS_BW_ROUTE10 1074
#define MUS_BW_VICTORY_ROAD 1075
#define MUS_BW_ENCOUNTER_ACE_TRAINER 1076
#define MUS_BW_POKEMON_LEAGUE 1077
#define MUS_BW_VS_ELITE_FOUR 1078
#define MUS_BW_N_CASTLE_APPEARS 1079
#define MUS_BW_N_CASTLE_BRIDGE 1080
#define MUS_BW_N_CASTLE 1081
#define MUS_BW_N_ROOM 1082
#define MUS_BW_LEGEND_COME 1083
#define MUS_BW_LEGEND_BORN 1084
#define MUS_BW_VS_RESHIRAM_ZEKROM 1085
#define MUS_BW_VS_N_2 1086
#define MUS_BW_GHETSIS 1087
#define MUS_BW_VS_GHETSIS 1088
#define MUS_BW_FAREWELL 1089
#define MUS_BW_CREDITS 1090
#define MUS_BW_LOOKER 1091
#define MUS_BW_OBTAIN_EGG 1092
#define MUS_BW_ROYAL_UNOVA 1093
#define MUS_BW_WFC 1094
#define MUS_BW_GLOBAL_TERMINAL 1095
#define MUS_BW_GTS 1096
#define MUS_BW_SPIN_TRADE 1097
#define MUS_BW_UNITY_TOWER 1098
#define MUS_BW_DEX_RATING_5 1099
#define MUS_BW_GEAR_STATION 1100
#define MUS_BW_BATTLE_SUBWAY 1101
#define MUS_BW_VS_SUBWAY_TRAINER 1102
#define MUS_BW_OBTAIN_B_POINTS 1103
#define MUS_BW_MUSICAL_THEATER 1104
#define MUS_BW_OBTAIN_ACCESSORY 1105
#define MUS_BW_MUSICAL_DRESS_UP 1106
#define MUS_BW_MUSICAL_CURTAIN_RAISES 1107
#define MUS_BW_MUSICAL_STARDOM 1108
#define MUS_BW_MUSICAL_FOREST_STROLL 1109
#define MUS_BW_MUSICAL_A_SWEET_SOIREE 1110
#define MUS_BW_MUSICAL_EXCITING_NIMBASA 1111
#define MUS_BW_MUSICAL_DLC_MUNNA 1112
#define MUS_BW_MUSICAL_DLC_SMASH 1113
#define MUS_BW_MUSICAL_DLC_FESTA 1114
#define MUS_BW_MUSICAL_DLC_RELIC 1115
#define MUS_BW_MUSICAL_DLC_RUNPA 1116
#define MUS_BW_FERRIS_WHEEL 1117
#define MUS_BW_FEELING_CHECK 1118
#define MUS_BW_FEELING_CHECK_HIGH 1119
#define MUS_BW_FEELING_CHECK_MEDIUM 1120
#define MUS_BW_FEELING_CHECK_LOW 1121
#define MUS_BW_VS_LEGEND 1122
#define MUS_BW_ANVILLE_TOWN 1123
#define MUS_BW_MARVELOUS_BRIDGE 1124
#define MUS_BW_ROUTE12_SPRING 1125
#define MUS_BW_ROUTE12_SUMMER 1126
#define MUS_BW_ROUTE12_AUTUMN 1127
#define MUS_BW_ROUTE12_WINTER 1128
#define MUS_BW_ENCOUNTER_CYCLIST 1129
#define MUS_BW_POKETRANSFER_LAB 1130
#define MUS_BW_POKETRANSFER_BOX 1131
#define MUS_BW_POKETRANSFER_GAME 1132
#define MUS_BW_ENCOUNTER_POKEFAN 1133
#define MUS_BW_BLACK_CITY 1134
#define MUS_BW_WHITE_FOREST 1135
#define MUS_BW_GAME_SYNC 1136
#define MUS_BW_ENTRALINK 1137
#define MUS_BW_FUNFEST_START 1138
#define MUS_BW_ENTRALINK_VISIT 1139
#define MUS_BW_FUNFEST_CLEAR 1140
#define MUS_BW_FUNFEST_FAILED 1141
#define MUS_BW_ENCOUNTER_GENTLEMAN 1142
#define MUS_BW_UNDELLA_SPRING 1143
#define MUS_BW_UNDELLA_SUMMER 1144
#define MUS_BW_CYNTHIA 1145
#define MUS_BW_VS_CYNTHIA 1146
#define MUS_BW_LOSTLORN_FOREST 1147
#define MUS_BW_VS_WILD_STRONG 1148
#define MUS_BW_SURF 1149
#define MUS_BW_ABYSSAL_RUINS 1150
#define MUS_BW_LACUNOSA 1151
#define MUS_BW_VILLAGE_BRIDGE 1152
#define MUS_BW_MYSTERY_GIFT 1153
#define MUS_BW_BATTLE_COMPETITION 1154
#define MUS_BW_ROCKET 1155
#define MUS_BW_VS_KYUREM 1156
#define MUS_BW_DEX_RATING_6 1157
#define MUS_BW_VS_CHAMPION 1158
#define MUS_BW_VICTORY_CHAMPION 1159
#define MUS_BW_HALL_OF_FAME 1160
#define MUS_BW_RELIC_SONG 1161
#define MUS_BW_VS_WCS_CHAMPION 1162
#define MUS_BW_OBTAIN_BERRY 1163

#define MUS_THPPORDX_FAITH_GBC_STYLE 1164
#define MUS_THPP_SPRINGLANE_GBC_STYLE 1165
#define MUS_THPP_PLAINASIA_GBC_STYLE 1166
#define MUS_THPPRF_GIRLS_SEALING_CLUB_GBC_STYLE 1167

#define MUS_NONE                    0xFFFF

#endif  // GUARD_CONSTANTS_SONGS_H
