SafariZone_West_Text_RestHouse::
    .string "REST HOUSE$"

SafariZone_West_Text_PleaseFindWardensLostTeeth::
    .string "REQUEST NOTICE\p"
    .string "Please find the\n"
    .string "SAFARI WARDENÙ\l"
    .string "lost GOLD TEETH.\l"
    .string "Theyàe around\l"
    .string "here somewhere.\p"
    .string "Reward offered!\n"
    .string "Contact: WARDEN$"

SafariZone_West_Text_SearchForSecretHouse::
    .string "TRAINER TIPS\n"
    .string "Zone Exploration\l"
    .string "Campaign!\p"
    .string "The Search for\n"
    .string "the SECRET HOUSE!$"

SafariZone_West_Text_AreaSign::
    .string "AREA 3\n"
    .string "EAST: CENTER AREA$"

