SilphCo_5F_Text_RocketsInUproarAboutIntruder::
    .string "TEAM ROCKET is\n"
    .string "in an uproar over\l"
    .string "some intruder.\l"
    .string "That`s you right?$"

SilphCo_5F_Text_YoureOurHeroThankYou::
    .string "TEAM ROCKET took\n"
    .string "off! You're our\l"
    .string "hero! Thank you!$"

SilphCo_5F_Text_Grunt1Intro::
    .string "I heard a kid was\n"
    .string "wandering around.$"

SilphCo_5F_Text_Grunt1Defeat::
    .string "ROCKET: Boom!$"

SilphCo_5F_Text_Grunt1PostBattle::
    .string "It's not smart\n"
    .string "to pick a fight\l"
    .string "with TEAM ROCKET!$"

SilphCo_5F_Text_BeauIntro::
    .string "We study POKé\n"
    .string "BALL technology\l"
    .string "on this floor!$"

SilphCo_5F_Text_BeauDefeat::
    .string "SCIENTIST: Dang!\n"
    .string "Blast it!$"

SilphCo_5F_Text_BeauPostBattle::
    .string "We worked on the\n"
    .string "ultimate POKé\l"
    .string "BALL which would\l"
    .string "catch anything!$"

SilphCo_5F_Text_DaltonIntro::
    .string "Whaaat? There\n"
    .string "shouldn't be any\n"
    .string "children here?$"

SilphCo_5F_Text_DaltonDefeat::
    .string "JUGGLER: Oh goodness!$"

SilphCo_5F_Text_DaltonPostBattle::
    .string "You're only on 5F.\n"
    .string "It's a long way to my BOSS!$"

SilphCo_5F_Text_Grunt2Intro::
    .string "Show TEAM ROCKET a little respect!$"

SilphCo_5F_Text_Grunt2Defeat::
    .string "Cough...\n"
    .string "Cough...$"

SilphCo_5F_Text_Grunt2PostBattle::
    .string "ROCKET: Which reminds me.\p"
    .string "KOFFING evolves into WEEZING!$"

SilphCo_5F_Text_PorygonFirstVRMon::
    .string "It's a POKéMON REPORT!\p"
    .string "POKéMON LAB created PORYGON,\n"
    .string "the first virtual reality POKéMON.$"

SilphCo_5F_Text_Over350TechniquesConfirmed::
    .string "It's a POKéMON REPORT!\p"
    .string "Over 160 POKéMON techniques have\n"
    .string "been confirmed.$"

SilphCo_5F_Text_SomeMonsEvolveWhenTraded::
    .string "It's a POKéMON REPORT!\p"
    .string "4 POKéMON evolve only when traded\n"
    .string "by link-cable.$"

SilphCo_5F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "5F$"

SilphCo_5F_Text_RocketBossLookingForStrongMons::
    .string "Those thugs that took over our\n"
    .string "building…\p"
    .string "Their BOSS said he was looking for\n"
    .string "strong POKéMON.\p"
    .string "I hope our PRESIDENT managed to\n"
    .string "avoid trouble…$"
