gOtherText_NewName::
    .string "NEW NAME$"

gNameChoice_Green::
    .string "BLUE$"

gNameChoice_Red::
    .string "RED$"

gNameChoice_Leaf::
    .string "LEAF$"

gNameChoice_Fire::
    .string "FIRE$"

gNameChoice_Gary::
    .string "GARY$"

gNameChoice_Kaz::
    .string "JOHN$"

gNameChoice_Toru::
    .string "TORU$"

gNameChoice_Ash::
    .string "ASH$"

gNameChoice_Kene::
    .string "JACK$"

gNameChoice_Geki::
    .string "GEKI$"

gNameChoice_Jak::
    .string "JAK$"

gNameChoice_Janne::
    .string "JANNE$"

gNameChoice_Jonn::
    .string "JONN$"

gNameChoice_Kamon::
    .string "KAMON$"

gNameChoice_Karl::
    .string "KARL$"

gNameChoice_Taylor::
    .string "TAYLOR$"

gNameChoice_Oscar::
    .string "OSCAR$"

gNameChoice_Hiro::
    .string "HIRO$"

gNameChoice_Max::
    .string "MAX$"

gNameChoice_Jon::
    .string "JON$"

gNameChoice_Ralph::
    .string "RALPH$"

gNameChoice_Kay::
    .string "KAY$"

gNameChoice_Tosh::
    .string "TOSH$"

gNameChoice_Roak::
    .string "ROAK$"

gNameChoice_Omi::
    .string "OMI$"

gNameChoice_Jodi::
    .string "JODI$"

gNameChoice_Amanda::
    .string "AMANDA$"

gNameChoice_Hillary::
    .string "HILLARY$"

gNameChoice_Makey::
    .string "MAKEY$"

gNameChoice_Michi::
    .string "MICHI$"

gNameChoice_Paula::
    .string "PAULA$"

gNameChoice_June::
    .string "JUNE$"

gNameChoice_Cassie::
    .string "CASSIE$"

gNameChoice_Rey::
    .string "REY$"

gNameChoice_Seda::
    .string "SEDA$"

gNameChoice_Kiko::
    .string "KIKO$"

gNameChoice_Mina::
    .string "MINA$"

gNameChoice_Norie::
    .string "NORIE$"

gNameChoice_Sai::
    .string "SAI$"

gNameChoice_Momo::
    .string "MOMO$"

gNameChoice_Suzi::
    .string "SUZI$"

gControlsGuide_Text_Intro::
    .string "The various buttons will be explained in\n"
    .string "the order of their importance.$"

gControlsGuide_Text_DPad::
    .string "Moves the main character.\n"
    .string "Also used to choose various data\n"
    .string "headings.$"

gControlsGuide_Text_AButton::
    .string "Used to confirm a choice, check\n"
    .string "things, chat, and scroll text.$"

gControlsGuide_Text_BButton::
    .string "Used to exit, cancel a choice,\n"
    .string "and cancel a mode.$"

gControlsGuide_Text_StartButton::
    .string "Press this button to open the\n"
    .string "MENU.$"

gControlsGuide_Text_SelectButton::
    .string "Used to shift items and to use\n"
    .string "a registered item.$"

gControlsGuide_Text_LRButtons::
    .string "If you need help playing the\n"
    .string "game, or on how to do things,\n"
    .string "press the L or R Button.$"

gOakSpeech_Text_AskPlayerGender::
    .string "Now tell me. Are you a boy?\n"
    .string "Or are you a girl?$"

gPikachuIntro_Text_Page1::

gPikachuIntro_Text_Page2::

gPikachuIntro_Text_Page3::

gOakSpeech_Text_WelcomeToTheWorld::
    .string "Hello there!\n"
    .string "Welcome to the\l"
    .string "world of POKéMON!\p"
    .string "My name is OAK!\n"
    .string "People call me\p"
    .string "the POKéMON PROF!$"

gOakSpeech_Text_ThisWorld::
    .string "This world is\n"
    .string "inhabited by\l"
    .string "creatures called\p"
    .string "POKéMON!$"

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "WIP$"

gOakSpeech_Text_IStudyPokemon::
    .string "For some people,\n"
    .string "POKéMON are\l"
    .string "pets. Others use\l"
    .string "them for fights.\p"
    .string "Myself...\n"
    .string "I study POKéMON\p"
    .string "as a profession.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "But first, tell me a\n"
    .string "little about yourself.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "First, what is\n"
    .string "your name?$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "Right! So your\n"
    .string "name is {PLAYER}!$"

gOakSpeech_Text_WhatWasHisName::
    .string "This is my grand-\n"
    .string "son. He's been\l"
    .string "your rival since\l"
    .string "you were a baby.\p"
    .string "...Erm, what is\n"
    .string "his name again?\p$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "Your rival's name, what was it now?$"

gOakSpeech_Text_ConfirmRivalName::
    .string "…Er, was it {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
    .string "That's right! I\n"
    .string "remember now! His\l"
    .string "name is {RIVAL}!$"

gOakSpeech_Text_LetsGo::
    .string "{PLAYER}!\p"
    .string "Your very own\n"
    .string "POKéMON legend is\l"
    .string "about to unfold!\p"
    .string "A world of dreams\n"
    .string "and adventures\l"
    .string "with POKéMON\p"
    .string "awaits! Let's go!$"
