Text_BootedUpPC::
	.string "{PLAYER} turned on\n"
	.string "the PC.$"

Text_AccessWhichPC::
	.string "Which PC should\n"
	.string "be accessed?$"

Text_AccessedSomeonesPC::
	.string "Accessed SomeoneÙ\n"
	.string "PC.$"

Text_OpenedPkmnStorage::
	.string "POKéMON Storage\n"
	.string "System opened.$"

Text_AccessedPlayersPC::
	.string "Accessed my PC.$"

Text_AccessedItemStorage::
	.string "Accessed Item\n"
	.string "Storage System.$"

Text_AccessedBillsPC::
	.string "Accessed BILLÙ PC.$"
