gText_WouldYouLikeToSaveTheGame::
	.string "Would you like to\n" 
	.string "save the game?$"

gText_AlreadySaveFile_WouldLikeToOverwrite::
	.string "There is already a\n"
	.string "saved file. Is it okay\n"
	.string "to overwrite it?$"

gText_SavingDontTurnOffThePower::
	.string "SAVING...\n"
	.string "DON'T TURN OFF THE POWER.$"

gText_PlayerSavedTheGame::
	.string "{PLAYER} saved the game.$"

gText_SaveFailed2::
	.string "セーブに　しっぱい　しました‥$"

gText_DifferentGameFile::
	.string "The older file will be\p"
	.string "erased to save. Okay?$"
