PokemonMansion_Text_PressSecretSwitchJP::
    .string "ひみつの　スイッチが　ある！\p"
    .string "おして　みますか？$"

PokemonMansion_Text_LetsTryIt::
    .string "おしてみよう！　‥ポチッとな$"

PokemonMansion_Text_GaveUpOnPressingSwitch::
    .string "おすのは　あきらめた$"

PokemonMansion_1F_Text_SimonIntro::
    .string "This place is\n"
    .string "like, huge!$"

PokemonMansion_1F_Text_SimonDefeat::
    .string "BURGLAR: Ayah!$"

PokemonMansion_1F_Text_SimonPostBattle::
    .string "I wonder where\n"
    .string "my partner went.$"

PokemonMansion_1F_Text_BraydonIntro::
    .string "My mentor once\n"
    .string "lived here.$"

PokemonMansion_1F_Text_BraydonDefeat::
    .string "SCIENTIST: Whew!\n"
    .string "Overwhelming!$"

PokemonMansion_1F_Text_BraydonPostBattle::
    .string "So, you're stuck?\n"
    .string "Try jumping off\l"
    .string "over there!$"

PokemonMansion_1F_Text_MewGaveBirthToMewtwo::
    .string "Diary: Feb. 6\n"
    .string "MEW gave birth.\p"
    .string "We named the\n"
    .string "newborn MEWTWO.$"

