PewterCity_Mart_Text_BoughtWeirdFishFromShadyGuy::
    .string "A shady, old man\n"
    .string "got me to but\l"
    .string "this really weird\l"
    .string "fish POKéMON!\p"
    .string "It's totally weak\n"
    .string "and it cost ¥500!$"

PewterCity_Mart_Text_GoodThingsIfRaiseMonsDiligently::
    .string "Good things can\n"
    .string "happen if you\l"
    .string "raise POKéMON\l"
    .string "diligently, even\l"
    .string "the weak ones!$"

