CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers::
    .string "POKéMON ability\n"
    .string "enhancers can be\l"
    .string "bought only here.\p"
    .string "Use CALCIUM to\n"
    .string "increase SPECIAL\l"
    .string "abilities.\p"
    .string "Use CARBOS to\n"
    .string "increase SPEED.$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers::
    .string "I'm here for\n"
    .string "POKéMON ability\l"
    .string "enhancers.\p"
    .string "PROTEIN increases\n"
    .string "ATTACK power.\p"
    .string "IRON increases\n"
    .string "DEFENSE!$"

CeladonCity_DepartmentStore_5F_Text_Drugstore::
    .string "5F: DRUG STORE$"

