SilphCo_7F_Text_HaveMonForSavingUs::
    .string "Oh! Hi! You're\n"
    .string "not a ROCKET! You\l"
    .string "came to save us?\l"
    .string "Why, thank you!\p"
    .string "I want you to\n"
    .string "have this POKéMON\l"
    .string "for saving us.$"

SilphCo_7F_Text_ObtainedLaprasFromEmployee::
    .string "{PLAYER} got\n"
    .string "LAPRAS.$"

SilphCo_7F_Text_ExplainLapras::
    .string "It's's LAPRAS. It's\n"
    .string "very intelligent.\p"
    .string "We kept it in our\n"
    .string "lab, but it will\l"
    .string "be much better\l"
    .string "off with you!\p"
    .string "I think you will\n"
    .string "be a good trainer\l"
    .string "for LAPRAS!\p"
    .string "It's a good\n"
    .string "swimmer. It'll\l"
    .string "give you a lift!$"

SilphCo_7F_Text_RocketBossWentToBoardroom::
    .string "TEAM ROCKET's\n"
    .string "BOSS went to the\l"
    .string "boardroom! Is our\l"
    .string "PRESIDENT OK?$"

SilphCo_7F_Text_OhNo::
    .string "あ‥　もう　もてないぞ$"

SilphCo_7F_Text_SavedAtLast::
    .string "たすかったよ　ありがと！$"

SilphCo_7F_Text_RocketsAfterMasterBall::
    .string "TEAM ROCKET was\n"
    .string "after the MASTER\l"
    .string "BALL which will\l"
    .string "catch any POKéMON!$"

SilphCo_7F_Text_CanceledMasterBallProject::
    .string "We canceled the\n"
    .string "MASTER BALL\l"
    .string "project because\l"
    .string "of TEAM ROCKET.$"

SilphCo_7F_Text_BadIfTeamRocketTookOver::
    .string "It would be bad\n"
    .string "if TEAM ROCKET\l"
    .string "took over SILPH\l"
    .string "or our POKéMON!$"

SilphCo_7F_Text_WowYouChasedOffTeamRocket::
    .string "Wow! You chased\n"
    .string "off TEAM ROCKET\l"
    .string "all by yourself?$"

SilphCo_7F_Text_ReallyDangerousHere::
    .string "You! It's really\n"
    .string "dangerous here!\l"
    .string "You came to save\l"
    .string "me? You can't!$"

SilphCo_7F_Text_ThankYouSoMuch::
    .string "Safe at last!\n"
    .string "Oh thank you!$"

SilphCo_7F_Text_Grunt3Intro::
    .string "Oh ho! I smell a\n"
    .string "little rat!$"

SilphCo_7F_Text_Grunt3Defeat::
    .string "ROCKET: Lights\n"
    .string "out!$"

SilphCo_7F_Text_Grunt3PostBattle::
    .string "You won't find my\n"
    .string "BOSS by just\l"
    .string "scurrying around!$"

SilphCo_7F_Text_JoshuaIntro::
    .string "Heheh!\p"
    .string "You mistook me for\n"
    .string "a SILPH worker?$"

SilphCo_7F_Text_JoshuaDefeat::
    .string "SCIENTIST: I'm\n"
    .string "done!$"

SilphCo_7F_Text_JoshuaPostBattle::
    .string "Despite your age,\n"
    .string "you are a skilled\l"
    .string "trainer!$"

SilphCo_7F_Text_Grunt1Intro::
    .string "I am one of the 4\n"
    .string "ROCKET BROTHERS!$"

SilphCo_7F_Text_Grunt1Defeat::
    .string "ROCKET: Aack!\n"
    .string "Brothers, I lost!$"

SilphCo_7F_Text_Grunt1PostBattle::
    .string "Doesn't matter.\n"
    .string "My brothers will\l"
    .string "repay the favor!$"

SilphCo_7F_Text_Grunt2Intro::
    .string "A child intruder?\n"
    .string "That must be you!$"

SilphCo_7F_Text_Grunt2Defeat::
    .string "ROCKET: Fine!\n"
    .string "I lost!$"

SilphCo_7F_Text_Grunt2PostBattle::
    .string "Go on home\n"
    .string "before my BOSS\l"
    .string "gets ticked off!$"

SilphCo_7F_Text_RivalWhatKeptYou::
    .string "{RIVAL}: What\n"
    .string "kept you {PLAYER}?$"

SilphCo_7F_Text_RivalIntro::
    .string "{RIVAL}: Hahaha!\n"
    .string "I thought you'd\l"
    .string "turn up if I\l"
    .string "waited here!\p"
    .string "I guess TEAM\n"
    .string "ROCKET slowed you\l"
    .string "down! Not that I\l"
    .string "care!\p"
    .string "I saw you in\n"
    .string "SAFFRON, so I\l"
    .string "decided to see if\l"
    .string "you got better!$"

SilphCo_7F_Text_RivalDefeat::
    .string "Oh ho!\n"
    .string "So, you are ready\l"
    .string "for BOSS ROCKET!$"

SilphCo_7F_Text_RivalVictory::
    .string "{RIVAL}“おまえなあ‥\p"
    .string "こんな　うでまえじゃ\n"
    .string "まだまだ‥\l"
    .string "いちにんまえ　とは　いえないぜ$"

SilphCo_7F_Text_RivalPostBattle::
    .string "Well, {PLAYER}!\p"
    .string "I'm moving on up\n"
    .string "and ahead!\p"
    .string "By checking my\n"
    .string "POKéDEX, I'm\l"
    .string "starting to see\l"
    .string "what's strong and\l"
    .string "how they evolve!\p"
    .string "I'm going to the\n"
    .string "POKéMON LEAGUE\l"
    .string "to boot out the\l"
    .string "ELITE FOUR!\p"
    .string "I'll become the\n"
    .string "world's most\l"
    .string "powerful trainer!\p"
    .string "{PLAYER}, well\n"
    .string "good luck to you!\l"
    .string "Don't sweat it!\l"
    .string "Smell ya!$"

SilphCo_7F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "7F$"

