Route8_WestEntrance_Text_ThirstyOnGuardDuty::
    .string "Iá on guard duty.\n"
    .string "Gee, Iá thirsty, though!\p"
    .string "Oh wait there, the roadÙ closed.$"

Route8_WestEntrance_Text_ThatTeaLooksTasty::
    .string "Whoa, boy!\n"
    .string "Iá parched!$"

Route8_WestEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "...\n"
    .string "Huh? I can have this drink?\p"
    .string "Gee, thanks!\l"
    .string "...\n"
    .string "Glug, glug...\p"
    .string "...\l"
    .string "Gulp...\n"
    .string "If you want to go to\p"
    .string "SAFFRON CITY...\l"
    .string "...\n"
    .string "You can go on through.\p"
    .string "IÛl share this with the\n"
    .string "other guards!$"

Route8_WestEntrance_Text_HiHowsItGoing::
    .string "Hi, thanks for the cool drinks!$"

