SaffronCity_House_Text_DontLookAtMyLetter::
    .string "Thank you for\n"
    .string "writing. I hope\l"
    .string "to see you soon!\p"
    .string "Hey! DonÑ look\n"
    .string "at my letter!$"

SaffronCity_House_Text_Pidgey::
    .string "PIDGEY: Kurukkoo!$"

SaffronCity_House_Text_GettingCopycatPokeDoll::
    .string "The COPYCAT is\n"
    .string "cute! Iá getting\l"
    .string "her a POKé DOLL!$"

SaffronCity_House_Text_ExplainPPUp::
    .string "I was given a PP\n"
    .string "UP as a gift.\p"
    .string "ItÙ used to for\n"
    .string "increasing the PP\l"
    .string "of techniques!$"

