SSAnne_2F_Room2_Text_BrooksIntro::
    .string "Competing against\n"
    .string "the young keeps\l"
    .string "me youthful.$"

SSAnne_2F_Room2_Text_BrooksDefeat::
    .string "GENTLEMAN: Good\n"
    .string "fight! Ah, I feel\l"
    .string "young again!$"

SSAnne_2F_Room2_Text_BrooksPostBattle::
    .string "15 years ago, I\n"
    .string "would have won!$"

SSAnne_2F_Room2_Text_DaleIntro::
    .string "Check out what I\n"
    .string "fished up!$"

SSAnne_2F_Room2_Text_DaleDefeat::
    .string "FISHERMAN: I'm\n"
    .string "all out!$"

SSAnne_2F_Room2_Text_DalePostBattle::
    .string "Party?\p"
    .string "The cruise ship's\n"
    .string "party should be\l"
    .string "over by now.$"

