Text_MetronomeTeach::
    .string "Tch-tch-tch!\n"
    .string "I'll teach you a nifty move.\p"
    .string "Teach it to a POKéMON, and watch\n"
    .string "the fun unfold!\p"
    .string "It's a move called METRONOME.\n"
    .string "Does it strike your fancy?$"

Text_MetronomeDeclined::
    .string "I tell you, it's a lot of fun!$"

Text_MetronomeWhichMon::
    .string "Okay!\n"
    .string "Which POKéMON should I teach?$"

Text_MetronomeTaught::
    .string "Tch-tch-tch!\n"
    .string "That's the sound of a METRONOME.\p"
    .string "It tweaks your POKéMON's brain into\n"
    .string "using moves it doesn't even know.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_HaveYouAFossilForMe::
    .string "Hiya!\p"
    .string "I am important\n"
    .string "doctor!\p"
    .string "I study here rare\n"
    .string "POKéMON fossils!\p"
    .string "You! Have you a\n"
    .string "fossil for me?$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoIsTooBad::
    .string "No! Is too bad!$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalkJP::
    .string "ちょっと　じかん　かかるよ！\p"
    .string "そこらへんを　すこし\n"
    .string "ブラブラ　してくると　よろしー！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilMonBackToLife::
    .string "Where were you?\p"
    .string "Your fossil is\n"
    .string "back to life!\p"
    .string "It was {STR_VAR_1}\n"
    .string "like I think!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ReceivedMonFromDoctor::
    .string "{PLAYER} got\n"
    .string "{STR_VAR_1}!$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoRoomForPokemon::
    .string "ポケモン　いっぱいで　もてないね！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ThatFossilIsOfMonMakeItLiveAgain::
    .string "Oh! That is\n"
    .string "{STR_VAR_2}!\p"
    .string "It is fossil of\n"
    .string "{STR_VAR_1}, a\l"
    .string "POKéMON that is\l"
    .string "already extinct!\p"
    .string "My Resurrection\n"
    .string "Machine will make\l"
    .string "that POKéMON live\l"
    .string "again!$"

@ TODO: Resolve text dump error below?
CinnabarIsland_PokemonLab_ExperimentRoom_Text_HandedFossilToWeirdDoctor::
    .string "So! You hurry and\n"
    .string "give me that!\p"
    .string "{PLAYER} handed over\n"
    .string "{STR_VAR_2}$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalk::
    .string "I take a little\n"
    .string "time!\p"
    .string "You go for walk a\n"
    .string "little while!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_YouComeAgain::
    .string "Aiyah! You come\n"
    .string "again!$"

