ThreeIsland_House2_Text_CantMakeThisSpoonBend::
    .string "Urrrrrrrrgggghhhh…\n"
    .string "Kwaaaaah!\p"
    .string "…ItÙ useless! I canÑ make this\n"
    .string "spoon bend with my mind.\p"
    .string "Maybe I really donÑ have any\n"
    .string "psychic powers.$"

ThreeIsland_House2_Text_IAdmireSabrina::
    .string "You know about a girl GYM LEADER\n"
    .string "in SAFFRON CITY?\p"
    .string "She uses PSYCHIC-type POKéMON,\n"
    .string "right?\p"
    .string "I admire her, I really do.\p"
    .string "Iße heard that sheÙ one cool\n"
    .string "customer and beautiful, too.$"

