FuchsiaCity_PokemonCenter_1F_Text_CantBecomeGoodTrainerWithOneMon::
    .string "You can't win\n"
    .string "with just one\l"
    .string "strong POKéMON.\p"
    .string "It's tough, but\n"
    .string "you have to raise\l"
    .string "them evenly.$"

FuchsiaCity_PokemonCenter_1F_Text_PokemonLeagueWestOfViridian::
    .string "There's a narrow\n"
    .string "trail west of\l"
    .string "VIRIDIAN CITY.\p"
    .string "It goes to POKéMON\n"
    .string "LEAGUE HQ.\l"
    .string "The HQ governs\l"
    .string "all TRAINERS.$"

FuchsiaCity_PokemonCenter_1F_Text_VisitSafariZoneForPokedex::
    .string "If you're studying POKéMON,\n"
    .string "visit the SAFARI ZONE.\p"
    .string "It has all sorts of rare POKéMON.$"

