Route6_NorthEntrance_Text_ThirstyOnGuardDuty::
    .string "I'm on guard duty.\n"
    .string "Gee, I'm thirsty, though!\p"
    .string "Oh wait there, the road's closed.$"

Route6_NorthEntrance_Text_ThatTeaLooksTasty::
    .string "Whoa, boy!\n"
    .string "I'm parched!$"

Route6_NorthEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "Huh? I can have this drink?\n"
    .string "Gee, thanks!\l"
    .string "… …\l"
    .string "Glug, glug…\l"
    .string "… …\l"
    .string "Gulp…\l"
    .string "If you want to go to SAFFRON\l"
    .string "CITY…\l"
    .string "… …\l"
    .string "You can go on through.\p"
    .string "I'll share this with the other\n"
    .string "guards!$"

Route6_NorthEntrance_Text_HiHowsItGoing::
    .string "Hi, how's it going?$"

