TwoIsland_PokemonCenter_1F_Text_HaveYouVisitedGameCorner::
    .string "Have you visited the GAME CORNER\n"
    .string "already?\p"
    .string "ItÙ no good to go alone.\n"
    .string "You have to take a friend along.$"

TwoIsland_PokemonCenter_1F_Text_OldLadyLivesOutOnCape::
    .string "Not many people live on\n"
    .string "TWO ISLAND.\p"
    .string "There is this old lady who lives\n"
    .string "out on the cape.\p"
    .string "SheÙ been there since I donÑ know\n"
    .string "when.$"

