Route5_SouthEntrance_Text_ThirstyOnGuardDuty::
    .string "I'm on guard duty.\n"
    .string "Gee, I'm thirsty,\l"
    .string "though!\p"
    .string "Oh wait there,\n"
    .string "the road's closed.$"

Route5_SouthEntrance_Text_ThatTeaLooksTasty::
    .string "Whoa, boy!\n"
    .string "I'm parched!$"

Route5_SouthEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "...\n"
    .string "Huh? I can have\l"
    .string "this drink?\p"
    .string "Gee, thanks!\n"
    .string "...\l"
    .string "Glug, glug...\l"
    .string "...\l"
    .string "Gulp...\p"
    .string "If you want to go\n"
    .string "to SAFFRON CITY...\l"
    .string "...\p"
    .string "You can go on\l"
    .string "through. I'll\l"
    .string "share this with\l"
    .string "the other guards!$"

Route5_SouthEntrance_Text_HiHowsItGoing::
    .string "Hi, thanks for\n"
    .string "the cool drinks!$"

