Route15_WestEntrance_2F_Text_GiveItemIfCaughtEnough::
    .string "Hi! Remember me?\n"
    .string "I'm PROF.OAK's AIDE!\p"
    .string "If you caught {STR_VAR_1} kinds\n"
    .string "of POKéMON, I'm supposed to\l"
    .string "give you an {STR_VAR_2}!\p"
    .string "So, {PLAYER}, have you caught at\p"
    .string "least {STR_VAR_1} kinds of POKéMON?\n"

Route15_WestEntrance_2F_Text_GreatHereYouGo::
    .string "Great! You have caught\n"
    .string "{STR_VAR_3} kinds of POKéMON!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"

Route15_WestEntrance_2F_Text_ReceivedItemFromAide::
    .string "{PLAYER} got the {STR_VAR_2}!$"

Route15_WestEntrance_2F_Text_ExplainExpShare::
    .string "EXP. SHARE is an item to be held\n"
    .string "by a POKéMON.\p"
    .string "The POKéMON will receive a share\n"
    .string "of the EXP. Points without having\l"
    .string "to battle.$"

Route15_WestEntrance_2F_Text_LargeShiningBird::
    .string "Looked into the binoculars...\n"
    .string "A large, shining bird is flying\p"
    .string "toward the sea.$"

Route15_WestEntrance_2F_Text_SmallIslandOnHorizon::
    .string "Looked into the binoculars.\n"
    .string "It looks like a small island!$"

