RockTunnel_1F_Text_LennyIntro::
    .string "This tunnel goes a long way, kid!$"

RockTunnel_1F_Text_LennyDefeat::
    .string "HIKER: Doh!\n"
    .string "You win!$"

RockTunnel_1F_Text_LennyPostBattle::
    .string "Watch for ONIX!\n"
    .string "It can put the squeeze on you!$"

RockTunnel_1F_Text_OliverIntro::
    .string "Hmm.\n"
    .string "Maybe Iá lost in here...$"

RockTunnel_1F_Text_OliverDefeat::
    .string "HIKER: Ease up!\n"
    .string "What am I doing?\l"
    .string "Which way is out?$"

RockTunnel_1F_Text_OliverPostBattle::
    .string "That sleeping POKéMON on ROUTE 12\n"
    .string "forced me to take this detour.$"

RockTunnel_1F_Text_LucasIntro::
    .string "Outsiders like you need to show me\n"
    .string "some respect!$"

RockTunnel_1F_Text_LucasDefeat::
    .string "HIKER: I give!$"

RockTunnel_1F_Text_LucasPostBattle::
    .string "Youàe talented enough to hike!$"

RockTunnel_1F_Text_AshtonIntro::
    .string "POKéMON fight!\n"
    .string "Ready, go!$"

RockTunnel_1F_Text_AshtonDefeat::
    .string "POKéMANIAC: Game over!$"

RockTunnel_1F_Text_AshtonPostBattle::
    .string "Oh well, IÛl get a ZUBAT as I go!$"

RockTunnel_1F_Text_LeahIntro::
    .string "Eek!\p"
    .string "DonÑ try anything funny in the\n"
    .string "dark!$"

RockTunnel_1F_Text_LeahDefeat::
    .string "JR.TRAINER♂: It was too dark!$"

RockTunnel_1F_Text_LeahPostBattle::
    .string "I saw a MACHOP in this tunnel!$"

RockTunnel_1F_Text_DanaIntro::
    .string "I came this far\n"
    .string "for POKéMON!$"

RockTunnel_1F_Text_DanaDefeat::
    .string "JR.TRAINER♂: Iá out of POKéMON!$"

RockTunnel_1F_Text_DanaPostBattle::
    .string "You looked cute and harmless!$"

RockTunnel_1F_Text_ArianaIntro::
    .string "You have POKéMON!\n"
    .string "LetÙ start!$"

RockTunnel_1F_Text_ArianaDefeat::
    .string "JR.TRAINER♂: You play hard!$"

RockTunnel_1F_Text_ArianaPostBattle::
    .string "Whew!\n"
    .string "Iá all sweaty now!$"

RockTunnel_1F_Text_RouteSign::
    .string "ROCK TUNNEL\n"
    .string "CERULEAN CITY - LAVENDER TOWN$"

