SixIsland_DottedHole_SapphireRoom_Text_FoundSapphire::
    .string "{PLAYER} found a SAPPHIRE!$"

SixIsland_DottedHole_SapphireRoom_Text_IWasRightInTailingYou::
    .string "Fufu… Fufufufu…\n"
    .string "I guessed right.\p"
    .string "I was right in tailing you!$"

SixIsland_DottedHole_SapphireRoom_Text_SellToTeamRocketTellPassword::
    .string "I knew that there was a SAPPHIRE\n"
    .string "here, so it belongs to me!\p"
    .string "IÛl sell it to TEAM ROCKET for\n"
    .string "serious money.\p"
    .string "…D-donÑ glare at me like that!\p"
    .string "If you want it back, why donÑ you\n"
    .string "go get it after I sell it?\p"
    .string "IÛl even tell you one of the\n"
    .string "passwords to TEAM ROCKETÙ\l"
    .string "WAREHOUSE.\p"
    .string "The WAREHOUSE password I know is\n"
    .string "“Yes, nah, CHANSEY.”\p"
    .string "Iá done.\n"
    .string "DonÑ think badly of me!$"

