CeladonCity_Condominiums_RoofRoom_Text_TheresNothingIDontKnow::
    .string "I know everything about the world\n"
    .string "of POKéMON in your GAME BOY!\p"
    .string "Get together with your friends\n"
    .string "and trade POKéMON!$"

CeladonCity_Condominiums_RoofRoom_Text_ObtainedAnEevee::
    .string "{PLAYER} got EEVEE!$"

CeladonCity_Condominiums_RoofRoom_Text_BoxIsFull::
    .string "ポケモンが　いっぱいだ\n"
    .string "ボックスを　かえて　きなさい$"

CeladonCity_Condominiums_RoofRoom_Text_WirelessAdapterLecture::
    .string "TRAINER TIPS\p"
    .string "Using a Game Link Cable$"

CeladonCity_Condominiums_RoofRoom_Text_ReadWhichHeading::
    .string "Which heading do you want to read?$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainWirelessClub::
    .string "The POKéMON WIRELESS CLUB is\n"
    .string "upstairs at any POKéMON CENTER.\p"
    .string "Visit one to link up with friend(s)\n"
    .string "using your Wireless Adapter.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainDirectCorner::
    .string "To link only with a friend, go to\n"
    .string "the DIRECT CORNER.\p"
    .string "It is the right counter at the\n"
    .string "POKéMON WIRELESS CLUB.\p"
    .string "Go into the TRADE CORNER or the\n"
    .string "COLOSSEUM with your friend.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainUnionRoom::
    .string "To link and communicate with\n"
    .string "anyone, go to the UNION ROOM.\p"
    .string "It is the left counter at the\n"
    .string "POKéMON WIRELESS CLUB.\p"
    .string "Go to the UNION ROOM and enjoy\n"
    .string "meeting other TRAINERS.$"

CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs::
    .string "It's a pamphlet on TMs.\p"
    .string "...\p"
    .string "There are 50 TMs in all.\p"
    .string "There are also 5 HMs that\n"
    .string "can be used repeatedly.\p"
    .string "SILPH CO.$"

