SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale::
    .string "{PLAYER}: Hi! Do\n"
    .string "you like POKéMON?\p"
    .string "{PLAYER}: Uh no, I\n"
    .string "just asked you.\p"
    .string "{PLAYER}: Huh?\n"
    .string "You're strange!\p"
    .string "COPYCAT: Hmm?\n"
    .string "Quit mimicking?\p"
    .string "But, that's my\n"
    .string "favorite hobby!$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale::
    .string "{PLAYER}: Hi! Do\n"
    .string "you like POKéMON?\p"
    .string "{PLAYER}: Uh no, I\n"
    .string "just asked you.\p"
    .string "{PLAYER}: Huh?\n"
    .string "You're strange!\p"
    .string "COPYCAT: Hmm?\n"
    .string "Quit mimicking?\p"
    .string "But, that's my\n"
    .string "favorite hobby!$"

Text_MimicTeach::
    .string "Oh wow!\n"
    .string "A POKé DOLL!\p"
    .string "For me?\n"
    .string "Thank you!\p"
    .string "You can have\n"
    .string "this, then!$"

Text_MimicDeclined::
    .string "Don't you like MIMIC?$"

Text_MimicWhichMon::
    .string "I really love MIMIC!\n"
    .string "Who's going to learn it?$"

Text_MimicTaughtMale::
    .string "{PLAYER}: Hi!\n"
    .string "Thanks for earlier!\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it that fun to mimic my\n"
    .string "every move?\p"
    .string "COPYCAT: You bet!\n"
    .string "It's a scream!$"

Text_MimicTaughtFemale::
    .string "{PLAYER}: Hi!\n"
    .string "Thanks for what you did for us.\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it really that fun to\n"
    .string "copy what I say and do?\p"
    .string "COPYCAT: You bet!\n"
    .string "It's a scream!$"

SaffronCity_CopycatsHouse_2F_Text_TooMuchInBag::
    .string "にもつが　いっぱいね！$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMaleJP::
    .string "{PLAYER}“やあ！　こんにちは！\n"
    .string "きみ　ポケモン　すきかい？\p"
    .string "{PLAYER}“ぼく　じゃなくって\n"
    .string "きみに　きいてるんだ　けど\p"
    .string "{PLAYER}“‥‥　えー　なんだよ！\n"
    .string "ヘンな　やつ　だなあ！\p"
    .string "モノマネむすめ“‥‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし　\n"
    .string "ものまね　しゅみ　なんだ　もん！”$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemaleJP::
    .string "{PLAYER}“こんにちは！\n"
    .string "ポケモン　すきなのね？\p"
    .string "{PLAYER}“わたし　じゃなくって\n"
    .string "あなたに　きいてるんだ　けど\p"
    .string "{PLAYER}“‥　えー　なんなの！\n"
    .string "おかしなこ　ねー！\p"
    .string "モノマネむすめ“‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし\n"
    .string "ものまね　しゅみ　なんだ　もん！$"

SaffronCity_CopycatsHouse_2F_Text_Doduo::
    .string "DODUO: Giiih!\p"
    .string "PRETTY MIRROR ON THE WALL,\n"
    .string "WHO IS THE FAIREST ONE OF ALL?$"

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll::
    .string "This is a rare POKéMON!\n"
    .string "Huh? It's only a doll!$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket::
    .string "A game with MARIO wearing a bucket\n"
    .string "on his head!$"

SaffronCity_CopycatsHouse_2F_Text_MySecrets::
    .string "...\p"
    .string "My Secrets!\p"
    .string "Skill: Mimicry!\n"
    .string "Hobby: Collecting dolls!\l"
    .string "Favorite POKéMON: CLEFAIRY!$"

SaffronCity_CopycatsHouse_2F_Text_HuhCantSee::
    .string "？　みえないぞ‥$"
