Route16_House_Text_FoundMySecretRetreat::
    .string "Oh, youße found my\n"
    .string "secret retreat!\p"
    .string "Please donÑ tell\n"
    .string "anyone Iá here.\l"
    .string "IÛl make it up\l"
    .string "to you with this!$"

Route16_House_Text_ReceivedHM02FromGirl::
    .string "{PLAYER} received\n"
    .string "HM02!$"

Route16_House_Text_ExplainHM02::
    .string "HM02 is FLY.\n"
    .string "It will take you\l"
    .string "back to any town.\p"
    .string "Put it to good\n"
    .string "use.$"

Route16_House_Text_DontHaveAnyRoomForThis::
    .string "You donÑ have any\n"
    .string "room for this.$"

Route16_House_Text_Fearow::
    .string "FEAROW: Kyueen!$"

