#include "global.h"
#include "constants/moves.h"

const u8 gMoveDescription_Pound[] = _("No special\neffect.");
const u8 gMoveDescription_KarateChop[] = _("Has a high\ncritical-hit\nratio.");
const u8 gMoveDescription_DoubleSlap[] = _("No special\neffect.");
const u8 gMoveDescription_CometPunch[] = _("No special\neffect.");
const u8 gMoveDescription_MegaPunch[] = _("No special\neffect.");
const u8 gMoveDescription_PayDay[] = _("Money is earned\nafter battle.");
const u8 gMoveDescription_FirePunch[] = _("May leave the\nfoe with a burn.");
const u8 gMoveDescription_IcePunch[] = _("May leave the\nfoe frozen.");
const u8 gMoveDescription_ThunderPunch[] = _("May leave the\nfoe paralyzed.");
const u8 gMoveDescription_Scratch[] = _("No special\neffect.");
const u8 gMoveDescription_ViceGrip[] = _("No special\neffect.");
const u8 gMoveDescription_Guillotine[] = _("The foe will\nfaint if\nit hits.");
const u8 gMoveDescription_RazorWind[] = _("Has a high\ncritical-hit\nratio.");
const u8 gMoveDescription_SwordsDance[] = _("Sharply raises\nATTACK.");
const u8 gMoveDescription_Cut[] = _("Use it to cut\ndown thin\ntrees and\ngrass.");
const u8 gMoveDescription_Gust[] = _("No special\neffect.");
const u8 gMoveDescription_WingAttack[] = _("No special\neffect.");
const u8 gMoveDescription_Whirlwind[] = _("The foe is\nmade to switch\nout. Ends wild\nbattles.");
const u8 gMoveDescription_Fly[] = _("Hits on the\n2nd turn. Use\nit to fly to\na known town.");
const u8 gMoveDescription_Bind[] = _("Binds the foe for\n2 to 5 turns.");
const u8 gMoveDescription_Slam[] = _("No special\neffect.");
const u8 gMoveDescription_VineWhip[] = _("No special\neffect.");
const u8 gMoveDescription_Stomp[] = _("May make the\nfoe flinch.");
const u8 gMoveDescription_DoubleKick[] = _("No special\neffect.");
const u8 gMoveDescription_MegaKick[] = _("No special\neffect.");
const u8 gMoveDescription_JumpKick[] = _("If it misses, the\nuser hurts itself.");
const u8 gMoveDescription_RollingKick[] = _("May make the\nfoe flinch.");
const u8 gMoveDescription_SandAttack[] = _("Reduces the\nfoeÙ accuracy.");
const u8 gMoveDescription_Headbutt[] = _("May make the\nfoe flinch.");
const u8 gMoveDescription_HornAttack[] = _("No special\neffect.");
const u8 gMoveDescription_FuryAttack[] = _("No special\neffect.");
const u8 gMoveDescription_HornDrill[] = _("The foe will\nfaint if\nit hits.");
const u8 gMoveDescription_Tackle[] = _("No special\neffect.");
const u8 gMoveDescription_BodySlam[] = _("May leave the\nfoe paralyzed.");
const u8 gMoveDescription_Wrap[] = _("No special\neffect.");
const u8 gMoveDescription_TakeDown[] = _("Hurts the\nuser a little.");
const u8 gMoveDescription_Thrash[] = _("Rampages 2 to\n3 turns,\nthen becomes\nconfused.");
const u8 gMoveDescription_DoubleEdge[] = _("Hurts the user\na little.");
const u8 gMoveDescription_TailWhip[] = _("Lowers the foeÙ\nDEFENSE.");
const u8 gMoveDescription_PoisonSting[] = _("May poison\nthe foe.");
const u8 gMoveDescription_Twineedle[] = _("May poison the\nfoe.");
const u8 gMoveDescription_PinMissile[] = _("No special\neffect.");
const u8 gMoveDescription_Leer[] = _("Lowers the foeÙ\nDEFENSE.");
const u8 gMoveDescription_Bite[] = _("May make the\nfoe flinch.");
const u8 gMoveDescription_Growl[] = _("Loweres the foeÙ\nATTACK.");
const u8 gMoveDescription_Roar[] = _("Forces the foe\nto switch out.\nIn the wild,\nthe battle ends.");
const u8 gMoveDescription_Sing[] = _("May leave the\nfoe asleep.");
const u8 gMoveDescription_Supersonic[] = _("May confuse the\nfoe.");
const u8 gMoveDescription_SonicBoom[] = _("Inflicts 20 HP\ndamage.");
const u8 gMoveDescription_Disable[] = _("Disables the\nfoeÙ last\nused move for\na few turns.");
const u8 gMoveDescription_Acid[] = _("May lower the\nfoeÙ DEFENSE.");
const u8 gMoveDescription_Ember[] = _("May leave the\nfoe burned.");
const u8 gMoveDescription_Flamethrower[] = _("May leave the\nfoe burned.");
const u8 gMoveDescription_Mist[] = _("The ally party\nis protected\nfrom stat\nreductions.");
const u8 gMoveDescription_WaterGun[] = _("No special\neffect.");
const u8 gMoveDescription_HydroPump[] = _("No special\neffect.");
const u8 gMoveDescription_Surf[] = _("Use it to surf\nacross water.");
const u8 gMoveDescription_IceBeam[] = _("May leave the\nfoe frozen.");
const u8 gMoveDescription_Blizzard[] = _("May leave the\nfoe frozen.");
const u8 gMoveDescription_Psybeam[] = _("May leave the\nfoe confused.");
const u8 gMoveDescription_BubbleBeam[] = _("May lower the\nfoeÙ SPEED.");
const u8 gMoveDescription_AuroraBeam[] = _("May lower the\nfoeÙ ATTACK.");
const u8 gMoveDescription_HyperBeam[] = _("Makes the user\nrest on the\nnext turn.");
const u8 gMoveDescription_Peck[] = _("No special\neffect.");
const u8 gMoveDescription_DrillPeck[] = _("No special\neffect.");
const u8 gMoveDescription_Submission[] = _("Hurts the\nuser a little.");
const u8 gMoveDescription_LowKick[] = _("Inflicts more\ndamage on\nheavier foes.");
const u8 gMoveDescription_Counter[] = _("Counters any\nphysical hit\nwith double\nthe damage.");
const u8 gMoveDescription_SeismicToss[] = _("Causes damage\nmatching the\nuserÙ level.");
const u8 gMoveDescription_Strength[] = _("Use it to push\nboulders.");
const u8 gMoveDescription_Absorb[] = _("Absorbs half\nthe damage it\ninflicted to\nrestore HP.");
const u8 gMoveDescription_MegaDrain[] = _("Absorbs half\nthe damage it\ninflicted to\nrestore HP.");
const u8 gMoveDescription_LeechSeed[] = _("Steals some HP\nfor the user\non every turn.");
const u8 gMoveDescription_Growth[] = _("Raises the\nuserÙ SP.ATK.");
const u8 gMoveDescription_RazorLeaf[] = _("Has a high\ncritical-hit\nratio.");
const u8 gMoveDescription_SolarBeam[] = _("Blasts the foe\nwith absorbed\nenergy in the\n2nd turn.");
const u8 gMoveDescription_PoisonPowder[] = _("May poison\nthe foe.");
const u8 gMoveDescription_StunSpore[] = _("May paralyze\nthe foe.");
const u8 gMoveDescription_SleepPowder[] = _("May put the\nfoe to sleep.");
const u8 gMoveDescription_PetalDance[] = _("Attack for\n2 to 3\nturns, then\nget confused.");
const u8 gMoveDescription_StringShot[] = _("Lowers the\nfoeÙ SPEED.");
const u8 gMoveDescription_DragonRage[] = _("Will always\ninflict 40 HP\ndamage.");
const u8 gMoveDescription_FireSpin[] = _("Traps the foe\nin a spiral of\nfire for 2\nto 5 turns.");
const u8 gMoveDescription_ThunderShock[] = _("May leave the\nfoe paralyzed.");
const u8 gMoveDescription_Thunderbolt[] = _("May leave the\nfoe paralyzed.");
const u8 gMoveDescription_ThunderWave[] = _("Will leave the\nfoe paralyzed.");
const u8 gMoveDescription_Thunder[] = _("May leave the\nfoe paralyzed.");
const u8 gMoveDescription_RockThrow[] = _("No special\neffect.");
const u8 gMoveDescription_Earthquake[] = _("Strikes all\nother POKéMON\nin battle.");
const u8 gMoveDescription_Fissure[] = _("The foe faints\nif it hits.");
const u8 gMoveDescription_Dig[] = _("Hits on the\n2nd turn. Can\nbe used to\nexit dungeons.");
const u8 gMoveDescription_Toxic[] = _("Badly poisons\nthe foe,\nworsens every\nturn.");
const u8 gMoveDescription_Confusion[] = _("May leave the\nfoe confused.");
const u8 gMoveDescription_Psychic[] = _("May lower the\nfoeÙ SP.DEF.");
const u8 gMoveDescription_Hypnosis[] = _("Will put the\nfoe to sleep.");
const u8 gMoveDescription_Meditate[] = _("Raises the\nuserÙ ATTACK.");
const u8 gMoveDescription_Agility[] = _("Raises the\nuserÙ SPEED.");
const u8 gMoveDescription_QuickAttack[] = _("Will strike\nfirst.");
const u8 gMoveDescription_Rage[] = _("Becomes more\npowerful each\ntime the user\nis hit in\nbattle.");
const u8 gMoveDescription_Teleport[] = _("Flee from wild\nPOKéMON. Also\nwarps to a\nPOKé CENTER.");
const u8 gMoveDescription_NightShade[] = _("Damage matches\nthe userÙ\nlevel.");
const u8 gMoveDescription_Mimic[] = _("Copies the\nfoeÙ last\nused move.");
const u8 gMoveDescription_Screech[] = _("Sharply lower\nthe foeÙ\nDEFENSE.");
const u8 gMoveDescription_DoubleTeam[] = _("Raises the\nuserÙ\nevasiveness.");
const u8 gMoveDescription_Recover[] = _("Restores HP by\nup to half of\nthe userÙ\nmaximum HP.");
const u8 gMoveDescription_Harden[] = _("Raises the\nuserÙ\nDEFENSE.");
const u8 gMoveDescription_Minimize[] = _("Raises the\nuserÙ\nevasiveness.");
const u8 gMoveDescription_Smokescreen[] = _("Lowers the\nfoeÙ\naccuracy.");
const u8 gMoveDescription_ConfuseRay[] = _("Will leave\nthe foe\nconfused.");
const u8 gMoveDescription_Withdraw[] = _("Raises the\nuserÙ\nDEFENSE.");
const u8 gMoveDescription_DefenseCurl[] = _("Raises the\nuserÙ\nDEFENSE.");
const u8 gMoveDescription_Barrier[] = _("Sharply raises\nthe userÙ\nDEFENSE.");
const u8 gMoveDescription_LightScreen[] = _("Cuts damage\nfrom SP.ATK\nattacks for\n5 turns.");
const u8 gMoveDescription_Haze[] = _("Eliminates all\nstat changes\nfor POKéMON\nin battle.");
const u8 gMoveDescription_Reflect[] = _("Lowers damage\nfrom physical\nattacks for\n5 turns.");
const u8 gMoveDescription_FocusEnergy[] = _("Raises the\nuserÙ\ncritical-hit\nratio.");
const u8 gMoveDescription_Bide[] = _("Endure attacks\nfor 2 turns,\nthen strike\nback double.");
const u8 gMoveDescription_Metronome[] = _("Use any move\nat random.");
const u8 gMoveDescription_MirrorMove[] = _("Counters the\nfoeÙ last\nused move with\nthe same move.");
const u8 gMoveDescription_SelfDestruct[] = _("Makes the\nuser faint.");
const u8 gMoveDescription_EggBomb[] = _("No special\neffect.");
const u8 gMoveDescription_Lick[] = _("May leave the\nfoe paralyzed.");
const u8 gMoveDescription_Smog[] = _("May poison\nthe foe.");
const u8 gMoveDescription_Sludge[] = _("May poison\nthe foe.");
const u8 gMoveDescription_BoneClub[] = _("May make the\nfoe flinch.");
const u8 gMoveDescription_FireBlast[] = _("May leave the\nfoe with a\nburn.");
const u8 gMoveDescription_Waterfall[] = _("Can be used to\nclimb a\nwaterfall.");
const u8 gMoveDescription_Clamp[] = _("Squeezes the\nfoe for 2 to\n5 turns.");
const u8 gMoveDescription_Swift[] = _("Never misses.");
const u8 gMoveDescription_SkullBash[] = _("Raises DEFENSE\nthe 1st turn,\nthen attacks\nthe 2nd turn.");
const u8 gMoveDescription_SpikeCannon[] = _("Strikes 2 to\n5 times.");
const u8 gMoveDescription_Constrict[] = _("May lower the\nfoeÙ SPEED.");
const u8 gMoveDescription_Amnesia[] = _("Sharply raises\nSP.DEF.");
const u8 gMoveDescription_Kinesis[] = _("May lower the\nfoeÙ\naccuracy.");
const u8 gMoveDescription_SoftBoiled[] = _("Heal by up to\n1/2 HP. Can be\nused to heal\nan ally.");
const u8 gMoveDescription_HiJumpKick[] = _("Damages the\nuser if it\nmisses.");
const u8 gMoveDescription_Glare[] = _("Will leave the\nfoe paralyzed.");
const u8 gMoveDescription_DreamEater[] = _("Absorb HP\nfrom a\nsleeping foe.");
const u8 gMoveDescription_PoisonGas[] = _("May poison\nthe foe.");
const u8 gMoveDescription_Barrage[] = _("Strikes 2 to\n5 times.");
const u8 gMoveDescription_LeechLife[] = _("Absorb half\nthe damage\ninflicted to\nrestore HP.");
const u8 gMoveDescription_LovelyKiss[] = _("Will put the\nfoe to sleep.");
const u8 gMoveDescription_SkyAttack[] = _("2-turn attack.\nHigh critical-\nhit ratio. Foe\nmay flinch.");
const u8 gMoveDescription_Transform[] = _("Transform into\na copy of the\nfoe with the\nsame moves.");
const u8 gMoveDescription_Bubble[] = _("May lower the\nfoeÙ SPEED.");
const u8 gMoveDescription_DizzyPunch[] = _("May leave the\nfoe confused.");
const u8 gMoveDescription_Spore[] = _("Will put the\nfoe to sleep.");
const u8 gMoveDescription_Flash[] = _("Lowers the foeÙ\naccuracy. Use\nto illuminate\ncaves.");
const u8 gMoveDescription_Psywave[] = _("Damage varies\nwith each use.");
const u8 gMoveDescription_Splash[] = _("No special\neffect.");
const u8 gMoveDescription_AcidArmor[] = _("Raises the\nuserÙ\nDEFENSE.");
const u8 gMoveDescription_Crabhammer[] = _("Has a high\ncritical-hit\nratio.");
const u8 gMoveDescription_Explosion[] = _("The user\nfaints.");
const u8 gMoveDescription_FurySwipes[] = _("Hits 2 to\n5 times.");
const u8 gMoveDescription_Bonemerang[] = _("Hits the foe\ntwice.");
const u8 gMoveDescription_Rest[] = _("Sleep for 2\nturns to fully\nheal HP and\nstatus.");
const u8 gMoveDescription_RockSlide[] = _("May make the\nfoe flinch.");
const u8 gMoveDescription_HyperFang[] = _("May make the\nfoe flinch.");
const u8 gMoveDescription_Sharpen[] = _("Raises ATTACK.");
const u8 gMoveDescription_Conversion[] = _("Change type to\nmatch the type\nof one of your\nmoves.");
const u8 gMoveDescription_TriAttack[] = _("May paralyze,\nburn, or\nfreeze the\nfoe.");
const u8 gMoveDescription_SuperFang[] = _("Halves the\nfoeÙ HP.");
const u8 gMoveDescription_Slash[] = _("Has a high\ncritical-hit\nratio.");
const u8 gMoveDescription_Substitute[] = _("Create a decoy\nusing 1/4 of\nits full HP.");
const u8 gMoveDescription_Struggle[] = _("Hurts the user.");
const u8 gMoveDescription_Sketch[] = _("Permanently\ncopy the move\nlast used by\nthe foe.");
const u8 gMoveDescription_TripleKick[] = _("3-hit attack.\nBecomes more\npowerful each\nsuccessive hit.");
const u8 gMoveDescription_Thief[] = _("May take the\nfoeÙ held\nitem.");
const u8 gMoveDescription_SpiderWeb[] = _("Ensnares the\nfoe so it\ndoesnÑ flee\nor switch out.");
const u8 gMoveDescription_MindReader[] = _("Ensures your\nnext attack\nhits the foe.");
const u8 gMoveDescription_Nightmare[] = _("Inflicts some\ndamage to a\nsleeping foe\nevery turn.");
const u8 gMoveDescription_FlameWheel[] = _("May leave the\nfoe with a\nburn.");
const u8 gMoveDescription_Snore[] = _("Can be used\nonly while\nasleep. May\ncause flinching.");
const u8 gMoveDescription_Curse[] = _("Effect is\ndifferent for\nGHOST-type\nusers.");
const u8 gMoveDescription_Flail[] = _("More powerful\nthe less HP\nthe user has.");
const u8 gMoveDescription_Conversion2[] = _("Change type to\nresist the\nlast taken\nattack.");
const u8 gMoveDescription_Aeroblast[] = _("Has a high\ncritical-hit\nratio.");
const u8 gMoveDescription_CottonSpore[] = _("Sharply lower\nthe foeÙ\nSPEED.");
const u8 gMoveDescription_Reversal[] = _("Becomes more\npowerful the\nless HP the\nuser has.");
const u8 gMoveDescription_Spite[] = _("Cuts 2 to 5 PP\nfrom the move\nlast used by\nthe foe.");
const u8 gMoveDescription_PowderSnow[] = _("May leave the\nfoe frozen.");
const u8 gMoveDescription_Protect[] = _("Evade all\nattacks. May\nfail if used\nin succession.");
const u8 gMoveDescription_MachPunch[] = _("Will strike\nfirst.");
const u8 gMoveDescription_ScaryFace[] = _("Sharply lower\nthe foeÙ\nSPEED.");
const u8 gMoveDescription_FaintAttack[] = _("Hits without\nfail.");
const u8 gMoveDescription_SweetKiss[] = _("Will leave the\nfoe confused.");
const u8 gMoveDescription_BellyDrum[] = _("Reduce max HP\nby half to\nmaximize\nATTACK.");
const u8 gMoveDescription_SludgeBomb[] = _("May poison the\ntarget.");
const u8 gMoveDescription_MudSlap[] = _("Will lower the\nfoeÙ\naccuracy.");
const u8 gMoveDescription_Octazooka[] = _("Will lower the\nfoeÙ\naccuracy.");
const u8 gMoveDescription_Spikes[] = _("Will hurt foes\nswitching in.");
const u8 gMoveDescription_ZapCannon[] = _("Will leave the\nfoe paralyzed.");
const u8 gMoveDescription_Foresight[] = _("Prevents the\nfoe from\nraising\nevasiveness.");
const u8 gMoveDescription_DestinyBond[] = _("If the user\nfaints, the\nfoe also\nfaints.");
const u8 gMoveDescription_PerishSong[] = _("Both battlers\nwill faint in\n3 turns.");
const u8 gMoveDescription_IcyWind[] = _("Will lower the\nfoeÙ\nSPEED.");
const u8 gMoveDescription_Detect[] = _("Evade all\nattacks. May\nfail if used\nin succession.");
const u8 gMoveDescription_BoneRush[] = _("Hits 2 to\n5 times.");
const u8 gMoveDescription_LockOn[] = _("The next move\nis guaranteed\nto hit.");
const u8 gMoveDescription_Outrage[] = _("Thrash for 2\nto 3 turns,\nthen become\nconfused.");
const u8 gMoveDescription_Sandstorm[] = _("Damages all\nbut ROCK or\nGROUND types\nfor 5 turns.");
const u8 gMoveDescription_GigaDrain[] = _("Absorb half\nthe inflicted\ndamage to\nrestore HP.");
const u8 gMoveDescription_Endure[] = _("Endure any\nhit. May\nfail if used\nin succession.");
const u8 gMoveDescription_Charm[] = _("Sharply lowers\nthe foeÙ\nATTACK.");
const u8 gMoveDescription_Rollout[] = _("5-turn attack\nthat becomes\nstronger each\nhit.");
const u8 gMoveDescription_FalseSwipe[] = _("Will leave the\nfoe with at\nleast 1 HP.");
const u8 gMoveDescription_Swagger[] = _("Will confuse\nthe foe and\nsharply raise\nits ATTACK.");
const u8 gMoveDescription_MilkDrink[] = _("Heal by up to\n1/2 HP. Can be\nused to heal\nan ally.");
const u8 gMoveDescription_Spark[] = _("May leave the\nfoe paralyzed.");
const u8 gMoveDescription_FuryCutter[] = _("Grows stronger\non each\nsuccessive\nhit.");
const u8 gMoveDescription_SteelWing[] = _("May raise\nDEFENSE.");
const u8 gMoveDescription_MeanLook[] = _("Prevents the\nfoe from\nescaping.");
const u8 gMoveDescription_Attract[] = _("A foe of the\nother gender\nis unlikely to\nattack.");
const u8 gMoveDescription_SleepTalk[] = _("If asleep, the\nuser randomly\nuses a move it\nknows.");
const u8 gMoveDescription_HealBell[] = _("Heals any\nstatus problem\nof all\nallies.");
const u8 gMoveDescription_Return[] = _("More powerful\nthe more the\nuser likes its\ntrainer.");
const u8 gMoveDescription_Present[] = _("May restore\nthe foeÙ HP.");
const u8 gMoveDescription_Frustration[] = _("More powerful\nthe less the\nuser likes its\ntrainer.");
const u8 gMoveDescription_Safeguard[] = _("Will protect\nagainst all\nstatus ailment\nfor 5 turns.");
const u8 gMoveDescription_PainSplit[] = _("Adds HP to the\nfoeÙ HP, then\nshares the\ntotal HP.");
const u8 gMoveDescription_SacredFire[] = _("May inflict a\nburn.");
const u8 gMoveDescription_Magnitude[] = _("Hits all\nstanding\nPOKéMON. Its\npower varies.");
const u8 gMoveDescription_DynamicPunch[] = _("Will leave the\nfoe confused.");
const u8 gMoveDescription_Megahorn[] = _("No special\neffect.");
const u8 gMoveDescription_DragonBreath[] = _("May leave the\nfoe paralyzes.");
const u8 gMoveDescription_BatonPass[] = _("Switch out,\npassing along\nany stat\nchanges.");
const u8 gMoveDescription_Encore[] = _("Makes the foe\nrepeat a move\nfor 2 to 6\nturns.");
const u8 gMoveDescription_Pursuit[] = _("Stronger when\na foe is\nswitching out.");
const u8 gMoveDescription_RapidSpin[] = _("Dispels BIND,\nWRAP, LEECH\nSEED, and\nSPIKES.");
const u8 gMoveDescription_SweetScent[] = _("Lower the foeÙ\nevasiveness.\nAlso attracts\nwild POKéMON.");
const u8 gMoveDescription_IronTail[] = _("May lower the\nfoeÙ\nDEFENSE.");
const u8 gMoveDescription_MetalClaw[] = _("May raise\nATTACK.");
const u8 gMoveDescription_VitalThrow[] = _("Attack after\nthe foe. In\nreturn, it\nwill not miss.");
const u8 gMoveDescription_MorningSun[] = _("Restore HP.\nThe amount of\nHP varies with\nthe weather.");
const u8 gMoveDescription_Synthesis[] = _("Restore HP.\nThe amount of\nHP varies with\nthe weather.");
const u8 gMoveDescription_Moonlight[] = _("Restore HP.\nThe amount of\nHP varies with\nthe weather.");
const u8 gMoveDescription_HiddenPower[] = _("Varies in type\nand intensity\ndepending on\nthe user.");
const u8 gMoveDescription_CrossChop[] = _("Hits twice.\nHas a high\ncritical-hit\nratio.");
const u8 gMoveDescription_Twister[] = _("May make the\nfoe flinch.");
const u8 gMoveDescription_RainDance[] = _("Powers up\nWATER-type\nmoves for 5\nturns.");
const u8 gMoveDescription_SunnyDay[] = _("Powers up\nFIRE-type\nmoves for 5\nturns.");
const u8 gMoveDescription_Crunch[] = _("May lower the\nfoeÙ SP.DEF.");
const u8 gMoveDescription_MirrorCoat[] = _("Pays back the\nfoeÙ special\nattack double.");
const u8 gMoveDescription_PsychUp[] = _("Copies any\nstat change\nmade by the\nfoe.");
const u8 gMoveDescription_ExtremeSpeed[] = _("Always strikes\nfirst.");
const u8 gMoveDescription_AncientPower[] = _("May raise all\nstats.");
const u8 gMoveDescription_ShadowBall[] = _("May lower the\nfoeÙ SP.DEF.");
const u8 gMoveDescription_FutureSight[] = _("The foe is hit\nafter 2 turns.");
const u8 gMoveDescription_RockSmash[] = _("May lower\nDEFENSE. Can\nbe used to\nbreak rocks.");
const u8 gMoveDescription_Whirlpool[] = _("Traps the foe\nin a whirlpool\nfor 2 to 5\nturns.");
const u8 gMoveDescription_BeatUp[] = _("All party\nPOKéMON join\nin the\nattack.");
const u8 gMoveDescription_FakeOut[] = _("Will cause\nflinching.\nUsable only on\nthe 1st turn.");
const u8 gMoveDescription_Uproar[] = _("Prevents sleep\nfor 2 to 5\nturns.");
const u8 gMoveDescription_Stockpile[] = _("Charge power\nfor use later.\nCan be used 3\ntimes.");
const u8 gMoveDescription_SpitUp[] = _("Attack using\nthe power\nbuilt up by\nSTOCKPILE.");
const u8 gMoveDescription_Swallow[] = _("Restore HP\nusing the\npower built up\nby STOCKPILE.");
const u8 gMoveDescription_HeatWave[] = _("May leave the\nfoe with a\nburn.");
const u8 gMoveDescription_Hail[] = _("Damages all\nbut ICE-types\nfor 5 turns.");
const u8 gMoveDescription_Torment[] = _("Makes the foe\nincapable of\nusing a move\nsuccessively.");
const u8 gMoveDescription_Flatter[] = _("Will confuse\nthe foe and\nraise its\nSP.ATK.");
const u8 gMoveDescription_WillOWisp[] = _("Will leave the\nfoe with a\nburn.");
const u8 gMoveDescription_Memento[] = _("Faint, sharply\nlower the\nfoeÙ ATTACK\nand SP.ATK.");
const u8 gMoveDescription_Facade[] = _("Raised damage\nif burned,\npoisoned, or\nparalyzed.");
const u8 gMoveDescription_FocusPunch[] = _("Hits last. The\nuser flinches\nif hit\nbeforehand.");
const u8 gMoveDescription_SmellingSalt[] = _("Will cure the\nfoeÙ paralysis\nin return for\nextra damage.");
const u8 gMoveDescription_FollowMe[] = _("Makes the foe\nattack only\nthe user.");
const u8 gMoveDescription_NaturePower[] = _("Type changes\ndepending on\nlocation.");
const u8 gMoveDescription_Charge[] = _("Charge power\nto boost the\nnext ELECTRIC\nmove.");
const u8 gMoveDescription_Taunt[] = _("The foe can\nuse only\nattack moves.");
const u8 gMoveDescription_HelpingHand[] = _("Boosts the\npower of the\nallyÙ attack\nin a battle.");
const u8 gMoveDescription_Trick[] = _("Trade held\nitems with the\nfoe.");
const u8 gMoveDescription_RolePlay[] = _("Copy the foeÙ\nability.");
const u8 gMoveDescription_Wish[] = _("Restore half\nthe full HP on\nthe next turn.");
const u8 gMoveDescription_Assist[] = _("Randomly uses a\nmove of an\nally POKéMON.");
const u8 gMoveDescription_Ingrain[] = _("Restore HP on\nevery turn,\nbut canÑ\nswitch out.");
const u8 gMoveDescription_Superpower[] = _("Lower ATTACK\nand DEFENSE.");
const u8 gMoveDescription_MagicCoat[] = _("Reflects the\nfoeÙ LEECH\nSEED and\nstatus-moves.");
const u8 gMoveDescription_Recycle[] = _("Recycle a used\nitem for use\nonce more.");
const u8 gMoveDescription_Revenge[] = _("Stronger if\nthe target has\nhurt the user.");
const u8 gMoveDescription_BrickBreak[] = _("Break any\nbarrier like\nLIGHT SCREEN\nand REFLECT.");
const u8 gMoveDescription_Yawn[] = _("Leaves the foe\nasleep on the\nnext turn.");
const u8 gMoveDescription_KnockOff[] = _("Remove the\nfoeÙ item for\nthis battle.");
const u8 gMoveDescription_Endeavor[] = _("Stronger when\nthe user has\nless HP than\nthe foe.");
const u8 gMoveDescription_Eruption[] = _("Stronger the\nmore HP the\nuser has.");
const u8 gMoveDescription_SkillSwap[] = _("Swap abilities\nwith the foe.");
const u8 gMoveDescription_Imprison[] = _("Prevent foes\nfrom using any\nmove known by\nthe user.");
const u8 gMoveDescription_Refresh[] = _("Cures the user\nof poisoning,\nburn, or\nparalysis.");
const u8 gMoveDescription_Grudge[] = _("If a foe makes\nthe user faint,\nits move\nloses all PP.");
const u8 gMoveDescription_Snatch[] = _("Steals the\neffects of a\nhealing or\nstatus-\nchanging move.");
const u8 gMoveDescription_SecretPower[] = _("May have an\neffect that\nvaries with\nterrain.");
const u8 gMoveDescription_Dive[] = _("Hide under\nwater and\nstrike next\nturn.");
const u8 gMoveDescription_ArmThrust[] = _("Hits 2 to 5\ntimes.");
const u8 gMoveDescription_Camouflage[] = _("Change type\nbased on\nterrain.");
const u8 gMoveDescription_TailGlow[] = _("Sharply raise\nSP.ATK.");
const u8 gMoveDescription_LusterPurge[] = _("May lower the\nfoeÙ SP.DEF.");
const u8 gMoveDescription_MistBall[] = _("May lower the\nfoeÙ SP.ATK.");
const u8 gMoveDescription_FeatherDance[] = _("Sharply lowers\nthe foeÙ\nATTACK");
const u8 gMoveDescription_TeeterDance[] = _("Will confuse\nall POKéMON in\nbattle.");
const u8 gMoveDescription_BlazeKick[] = _("Has a high\ncritical-hit\nratio. May\nburn the foe.");
const u8 gMoveDescription_MudSport[] = _("ELECTRIC-type\nmoves are weak\nwhile the user\nis in battle.");
const u8 gMoveDescription_IceBall[] = _("5-turn attack\nthat becomes\nstronger with\neach roll.");
const u8 gMoveDescription_NeedleArm[] = _("May make the\nfoe flinch.");
const u8 gMoveDescription_SlackOff[] = _("Restores the\nuserÙ HP by\n1/2 its full\nHP.");
const u8 gMoveDescription_HyperVoice[] = _("No special\neffect.");
const u8 gMoveDescription_PoisonFang[] = _("May leave the\nfoe badly\npoisoned.");
const u8 gMoveDescription_CrushClaw[] = _("May lower the\nfoeÙ DEFENSE.");
const u8 gMoveDescription_BlastBurn[] = _("The user canÑ\nmove on the\nnext turn.");
const u8 gMoveDescription_HydroCannon[] = _("The user canÑ\nmove\non the\nnext turn.");
const u8 gMoveDescription_MeteorMash[] = _("May raise\nATTACK.");
const u8 gMoveDescription_Astonish[] = _("May make the\nfoe flinch.");
const u8 gMoveDescription_WeatherBall[] = _("Power and type\nbased on\nweather.");
const u8 gMoveDescription_Aromatherapy[] = _("Heal every\nstatus problem\nin the userÙ\nparty.");
const u8 gMoveDescription_FakeTears[] = _("Sharply lower\nthe foeÙ\nSP.DEF.");
const u8 gMoveDescription_AirCutter[] = _("Has a high\ncritical-hit\nratio.");
const u8 gMoveDescription_Overheat[] = _("Sharply lowers\nthe userÙ\nSP.ATK.");
const u8 gMoveDescription_OdorSleuth[] = _("Prevents the\nfoe from\nraising\nevasiveness.");
const u8 gMoveDescription_RockTomb[] = _("Lowers the\nfoeÙ SPEED if\nit hits.");
const u8 gMoveDescription_SilverWind[] = _("May raise all\nstats.");
const u8 gMoveDescription_MetalSound[] = _("Sharply lower\nthe foeÙ\nSP.DEF.");
const u8 gMoveDescription_GrassWhistle[] = _("Leaves the foe\nasleep.");
const u8 gMoveDescription_Tickle[] = _("Will lower the\nfoeÙ ATTACK\nand DEFENSE.");
const u8 gMoveDescription_CosmicPower[] = _("Raises DEFENSE\nand SP.DEF.");
const u8 gMoveDescription_WaterSpout[] = _("Power based on\nthe userÙ\nremaining HP.");
const u8 gMoveDescription_SignalBeam[] = _("May leave the\nfoe confused.");
const u8 gMoveDescription_ShadowPunch[] = _("CanÑ be\nevaded.");
const u8 gMoveDescription_Extrasensory[] = _("May make the\nfoe flinch.");
const u8 gMoveDescription_SkyUppercut[] = _("CanÑ be\nevaded with\nFLY.");
const u8 gMoveDescription_SandTomb[] = _("Damages the\nfoe for 2 to\n5 turns.");
const u8 gMoveDescription_SheerCold[] = _("Causes the foe\nto faint if it\nhits.");
const u8 gMoveDescription_MuddyWater[] = _("May lower the\nfoeÙ accuracy.");
const u8 gMoveDescription_BulletSeed[] = _("2 to 5 seeds\nare shot at\nonce.");
const u8 gMoveDescription_AerialAce[] = _("CanÑ be\nevaded.");
const u8 gMoveDescription_IcicleSpear[] = _("Hits 2 to 5\ntimes.");
const u8 gMoveDescription_IronDefense[] = _("Sharply raise\nDEFENSE.");
const u8 gMoveDescription_Block[] = _("Prevents the\nfoe from\nswitching out\nor fleeing.");
const u8 gMoveDescription_Howl[] = _("Raise ATTACK.");
const u8 gMoveDescription_DragonClaw[] = _("No special\neffect.");
const u8 gMoveDescription_FrenzyPlant[] = _("The user canÑ\nmove on the\nnext turn.");
const u8 gMoveDescription_BulkUp[] = _("Raise ATTACK\nand DEFENSE.");
const u8 gMoveDescription_Bounce[] = _("Bounce on the\nfoe next turn.\nMay paralyze\nthe foe.");
const u8 gMoveDescription_MudShot[] = _("Lower the foeÙ\nSPEED.");
const u8 gMoveDescription_PoisonTail[] = _("Has a high\ncritical-hit\nratio. May\npoison the foe.");
const u8 gMoveDescription_Covet[] = _("Steals the\nfoeÙ held\nitem.");
const u8 gMoveDescription_VoltTackle[] = _("Hurts the user\na little.");
const u8 gMoveDescription_MagicalLeaf[] = _("CanÑ be\nevaded.");
const u8 gMoveDescription_WaterSport[] = _("FIRE-type\nmoves are weak\nwhile the user\nis in battle.");
const u8 gMoveDescription_CalmMind[] = _("Raise SP.ATK\nand SP.DEF.");
const u8 gMoveDescription_LeafBlade[] = _("Has a high\ncritical-hit\nratio.");
const u8 gMoveDescription_DragonDance[] = _("Raise ATTACK\nand SPEED.");
const u8 gMoveDescription_RockBlast[] = _("Hits 2 to 5\ntimes.");
const u8 gMoveDescription_ShockWave[] = _("CanÑ be\nevaded.");
const u8 gMoveDescription_WaterPulse[] = _("May leave the\nfoe confused.");
const u8 gMoveDescription_DoomDesire[] = _("Hits 2 turns\nafter use.");
const u8 gMoveDescription_PsychoBoost[] = _("Will sharply\nreduce the\nuserÙ SP.ATK.");

const u8 *const gMoveDescriptionPointers[MOVES_COUNT - 1] = {
    [MOVE_POUND         - 1] = gMoveDescription_Pound,
    [MOVE_KARATE_CHOP   - 1] = gMoveDescription_KarateChop,
    [MOVE_DOUBLE_SLAP   - 1] = gMoveDescription_DoubleSlap,
    [MOVE_COMET_PUNCH   - 1] = gMoveDescription_CometPunch,
    [MOVE_MEGA_PUNCH    - 1] = gMoveDescription_MegaPunch,
    [MOVE_PAY_DAY       - 1] = gMoveDescription_PayDay,
    [MOVE_FIRE_PUNCH    - 1] = gMoveDescription_FirePunch,
    [MOVE_ICE_PUNCH     - 1] = gMoveDescription_IcePunch,
    [MOVE_THUNDER_PUNCH - 1] = gMoveDescription_ThunderPunch,
    [MOVE_SCRATCH       - 1] = gMoveDescription_Scratch,
    [MOVE_VICE_GRIP     - 1] = gMoveDescription_ViceGrip,
    [MOVE_GUILLOTINE    - 1] = gMoveDescription_Guillotine,
    [MOVE_RAZOR_WIND    - 1] = gMoveDescription_RazorWind,
    [MOVE_SWORDS_DANCE  - 1] = gMoveDescription_SwordsDance,
    [MOVE_CUT           - 1] = gMoveDescription_Cut,
    [MOVE_GUST          - 1] = gMoveDescription_Gust,
    [MOVE_WING_ATTACK   - 1] = gMoveDescription_WingAttack,
    [MOVE_WHIRLWIND     - 1] = gMoveDescription_Whirlwind,
    [MOVE_FLY           - 1] = gMoveDescription_Fly,
    [MOVE_BIND          - 1] = gMoveDescription_Bind,
    [MOVE_SLAM          - 1] = gMoveDescription_Slam,
    [MOVE_VINE_WHIP     - 1] = gMoveDescription_VineWhip,
    [MOVE_STOMP         - 1] = gMoveDescription_Stomp,
    [MOVE_DOUBLE_KICK   - 1] = gMoveDescription_DoubleKick,
    [MOVE_MEGA_KICK     - 1] = gMoveDescription_MegaKick,
    [MOVE_JUMP_KICK     - 1] = gMoveDescription_JumpKick,
    [MOVE_ROLLING_KICK  - 1] = gMoveDescription_RollingKick,
    [MOVE_SAND_ATTACK   - 1] = gMoveDescription_SandAttack,
    [MOVE_HEADBUTT      - 1] = gMoveDescription_Headbutt,
    [MOVE_HORN_ATTACK   - 1] = gMoveDescription_HornAttack,
    [MOVE_FURY_ATTACK   - 1] = gMoveDescription_FuryAttack,
    [MOVE_HORN_DRILL    - 1] = gMoveDescription_HornDrill,
    [MOVE_TACKLE        - 1] = gMoveDescription_Tackle,
    [MOVE_BODY_SLAM     - 1] = gMoveDescription_BodySlam,
    [MOVE_WRAP          - 1] = gMoveDescription_Wrap,
    [MOVE_TAKE_DOWN     - 1] = gMoveDescription_TakeDown,
    [MOVE_THRASH        - 1] = gMoveDescription_Thrash,
    [MOVE_DOUBLE_EDGE   - 1] = gMoveDescription_DoubleEdge,
    [MOVE_TAIL_WHIP     - 1] = gMoveDescription_TailWhip,
    [MOVE_POISON_STING  - 1] = gMoveDescription_PoisonSting,
    [MOVE_TWINEEDLE     - 1] = gMoveDescription_Twineedle,
    [MOVE_PIN_MISSILE   - 1] = gMoveDescription_PinMissile,
    [MOVE_LEER          - 1] = gMoveDescription_Leer,
    [MOVE_BITE          - 1] = gMoveDescription_Bite,
    [MOVE_GROWL         - 1] = gMoveDescription_Growl,
    [MOVE_ROAR          - 1] = gMoveDescription_Roar,
    [MOVE_SING          - 1] = gMoveDescription_Sing,
    [MOVE_SUPERSONIC    - 1] = gMoveDescription_Supersonic,
    [MOVE_SONIC_BOOM    - 1] = gMoveDescription_SonicBoom,
    [MOVE_DISABLE       - 1] = gMoveDescription_Disable,
    [MOVE_ACID          - 1] = gMoveDescription_Acid,
    [MOVE_EMBER         - 1] = gMoveDescription_Ember,
    [MOVE_FLAMETHROWER  - 1] = gMoveDescription_Flamethrower,
    [MOVE_MIST          - 1] = gMoveDescription_Mist,
    [MOVE_WATER_GUN     - 1] = gMoveDescription_WaterGun,
    [MOVE_HYDRO_PUMP    - 1] = gMoveDescription_HydroPump,
    [MOVE_SURF          - 1] = gMoveDescription_Surf,
    [MOVE_ICE_BEAM      - 1] = gMoveDescription_IceBeam,
    [MOVE_BLIZZARD      - 1] = gMoveDescription_Blizzard,
    [MOVE_PSYBEAM       - 1] = gMoveDescription_Psybeam,
    [MOVE_BUBBLE_BEAM   - 1] = gMoveDescription_BubbleBeam,
    [MOVE_AURORA_BEAM   - 1] = gMoveDescription_AuroraBeam,
    [MOVE_HYPER_BEAM    - 1] = gMoveDescription_HyperBeam,
    [MOVE_PECK          - 1] = gMoveDescription_Peck,
    [MOVE_DRILL_PECK    - 1] = gMoveDescription_DrillPeck,
    [MOVE_SUBMISSION    - 1] = gMoveDescription_Submission,
    [MOVE_LOW_KICK      - 1] = gMoveDescription_LowKick,
    [MOVE_COUNTER       - 1] = gMoveDescription_Counter,
    [MOVE_SEISMIC_TOSS  - 1] = gMoveDescription_SeismicToss,
    [MOVE_STRENGTH      - 1] = gMoveDescription_Strength,
    [MOVE_ABSORB        - 1] = gMoveDescription_Absorb,
    [MOVE_MEGA_DRAIN    - 1] = gMoveDescription_MegaDrain,
    [MOVE_LEECH_SEED    - 1] = gMoveDescription_LeechSeed,
    [MOVE_GROWTH        - 1] = gMoveDescription_Growth,
    [MOVE_RAZOR_LEAF    - 1] = gMoveDescription_RazorLeaf,
    [MOVE_SOLARBEAM    - 1] = gMoveDescription_SolarBeam,
    [MOVE_POISON_POWDER - 1] = gMoveDescription_PoisonPowder,
    [MOVE_STUN_SPORE    - 1] = gMoveDescription_StunSpore,
    [MOVE_SLEEP_POWDER  - 1] = gMoveDescription_SleepPowder,
    [MOVE_PETAL_DANCE   - 1] = gMoveDescription_PetalDance,
    [MOVE_STRING_SHOT   - 1] = gMoveDescription_StringShot,
    [MOVE_DRAGON_RAGE   - 1] = gMoveDescription_DragonRage,
    [MOVE_FIRE_SPIN     - 1] = gMoveDescription_FireSpin,
    [MOVE_THUNDER_SHOCK - 1] = gMoveDescription_ThunderShock,
    [MOVE_THUNDERBOLT   - 1] = gMoveDescription_Thunderbolt,
    [MOVE_THUNDER_WAVE  - 1] = gMoveDescription_ThunderWave,
    [MOVE_THUNDER       - 1] = gMoveDescription_Thunder,
    [MOVE_ROCK_THROW    - 1] = gMoveDescription_RockThrow,
    [MOVE_EARTHQUAKE    - 1] = gMoveDescription_Earthquake,
    [MOVE_FISSURE       - 1] = gMoveDescription_Fissure,
    [MOVE_DIG           - 1] = gMoveDescription_Dig,
    [MOVE_TOXIC         - 1] = gMoveDescription_Toxic,
    [MOVE_CONFUSION     - 1] = gMoveDescription_Confusion,
    [MOVE_PSYCHIC       - 1] = gMoveDescription_Psychic,
    [MOVE_HYPNOSIS      - 1] = gMoveDescription_Hypnosis,
    [MOVE_MEDITATE      - 1] = gMoveDescription_Meditate,
    [MOVE_AGILITY       - 1] = gMoveDescription_Agility,
    [MOVE_QUICK_ATTACK  - 1] = gMoveDescription_QuickAttack,
    [MOVE_RAGE          - 1] = gMoveDescription_Rage,
    [MOVE_TELEPORT      - 1] = gMoveDescription_Teleport,
    [MOVE_NIGHT_SHADE   - 1] = gMoveDescription_NightShade,
    [MOVE_MIMIC         - 1] = gMoveDescription_Mimic,
    [MOVE_SCREECH       - 1] = gMoveDescription_Screech,
    [MOVE_DOUBLE_TEAM   - 1] = gMoveDescription_DoubleTeam,
    [MOVE_RECOVER       - 1] = gMoveDescription_Recover,
    [MOVE_HARDEN        - 1] = gMoveDescription_Harden,
    [MOVE_MINIMIZE      - 1] = gMoveDescription_Minimize,
    [MOVE_SMOKESCREEN   - 1] = gMoveDescription_Smokescreen,
    [MOVE_CONFUSE_RAY   - 1] = gMoveDescription_ConfuseRay,
    [MOVE_WITHDRAW      - 1] = gMoveDescription_Withdraw,
    [MOVE_DEFENSE_CURL  - 1] = gMoveDescription_DefenseCurl,
    [MOVE_BARRIER       - 1] = gMoveDescription_Barrier,
    [MOVE_LIGHT_SCREEN  - 1] = gMoveDescription_LightScreen,
    [MOVE_HAZE          - 1] = gMoveDescription_Haze,
    [MOVE_REFLECT       - 1] = gMoveDescription_Reflect,
    [MOVE_FOCUS_ENERGY  - 1] = gMoveDescription_FocusEnergy,
    [MOVE_BIDE          - 1] = gMoveDescription_Bide,
    [MOVE_METRONOME     - 1] = gMoveDescription_Metronome,
    [MOVE_MIRROR_MOVE   - 1] = gMoveDescription_MirrorMove,
    [MOVE_SELF_DESTRUCT - 1] = gMoveDescription_SelfDestruct,
    [MOVE_EGG_BOMB      - 1] = gMoveDescription_EggBomb,
    [MOVE_LICK          - 1] = gMoveDescription_Lick,
    [MOVE_SMOG          - 1] = gMoveDescription_Smog,
    [MOVE_SLUDGE        - 1] = gMoveDescription_Sludge,
    [MOVE_BONE_CLUB     - 1] = gMoveDescription_BoneClub,
    [MOVE_FIRE_BLAST    - 1] = gMoveDescription_FireBlast,
    [MOVE_WATERFALL     - 1] = gMoveDescription_Waterfall,
    [MOVE_CLAMP         - 1] = gMoveDescription_Clamp,
    [MOVE_SWIFT         - 1] = gMoveDescription_Swift,
    [MOVE_SKULL_BASH    - 1] = gMoveDescription_SkullBash,
    [MOVE_SPIKE_CANNON  - 1] = gMoveDescription_SpikeCannon,
    [MOVE_CONSTRICT     - 1] = gMoveDescription_Constrict,
    [MOVE_AMNESIA       - 1] = gMoveDescription_Amnesia,
    [MOVE_KINESIS       - 1] = gMoveDescription_Kinesis,
    [MOVE_SOFT_BOILED   - 1] = gMoveDescription_SoftBoiled,
    [MOVE_HI_JUMP_KICK  - 1] = gMoveDescription_HiJumpKick,
    [MOVE_GLARE         - 1] = gMoveDescription_Glare,
    [MOVE_DREAM_EATER   - 1] = gMoveDescription_DreamEater,
    [MOVE_POISON_GAS    - 1] = gMoveDescription_PoisonGas,
    [MOVE_BARRAGE       - 1] = gMoveDescription_Barrage,
    [MOVE_LEECH_LIFE    - 1] = gMoveDescription_LeechLife,
    [MOVE_LOVELY_KISS   - 1] = gMoveDescription_LovelyKiss,
    [MOVE_SKY_ATTACK    - 1] = gMoveDescription_SkyAttack,
    [MOVE_TRANSFORM     - 1] = gMoveDescription_Transform,
    [MOVE_BUBBLE        - 1] = gMoveDescription_Bubble,
    [MOVE_DIZZY_PUNCH   - 1] = gMoveDescription_DizzyPunch,
    [MOVE_SPORE         - 1] = gMoveDescription_Spore,
    [MOVE_FLASH         - 1] = gMoveDescription_Flash,
    [MOVE_PSYWAVE       - 1] = gMoveDescription_Psywave,
    [MOVE_SPLASH        - 1] = gMoveDescription_Splash,
    [MOVE_ACID_ARMOR    - 1] = gMoveDescription_AcidArmor,
    [MOVE_CRABHAMMER    - 1] = gMoveDescription_Crabhammer,
    [MOVE_EXPLOSION     - 1] = gMoveDescription_Explosion,
    [MOVE_FURY_SWIPES   - 1] = gMoveDescription_FurySwipes,
    [MOVE_BONEMERANG    - 1] = gMoveDescription_Bonemerang,
    [MOVE_REST          - 1] = gMoveDescription_Rest,
    [MOVE_ROCK_SLIDE    - 1] = gMoveDescription_RockSlide,
    [MOVE_HYPER_FANG    - 1] = gMoveDescription_HyperFang,
    [MOVE_SHARPEN       - 1] = gMoveDescription_Sharpen,
    [MOVE_CONVERSION    - 1] = gMoveDescription_Conversion,
    [MOVE_TRI_ATTACK    - 1] = gMoveDescription_TriAttack,
    [MOVE_SUPER_FANG    - 1] = gMoveDescription_SuperFang,
    [MOVE_SLASH         - 1] = gMoveDescription_Slash,
    [MOVE_SUBSTITUTE    - 1] = gMoveDescription_Substitute,
    [MOVE_STRUGGLE      - 1] = gMoveDescription_Struggle,
    [MOVE_SKETCH        - 1] = gMoveDescription_Sketch,
    [MOVE_TRIPLE_KICK   - 1] = gMoveDescription_TripleKick,
    [MOVE_THIEF         - 1] = gMoveDescription_Thief,
    [MOVE_SPIDER_WEB    - 1] = gMoveDescription_SpiderWeb,
    [MOVE_MIND_READER   - 1] = gMoveDescription_MindReader,
    [MOVE_NIGHTMARE     - 1] = gMoveDescription_Nightmare,
    [MOVE_FLAME_WHEEL   - 1] = gMoveDescription_FlameWheel,
    [MOVE_SNORE         - 1] = gMoveDescription_Snore,
    [MOVE_CURSE         - 1] = gMoveDescription_Curse,
    [MOVE_FLAIL         - 1] = gMoveDescription_Flail,
    [MOVE_CONVERSION_2  - 1] = gMoveDescription_Conversion2,
    [MOVE_AEROBLAST     - 1] = gMoveDescription_Aeroblast,
    [MOVE_COTTON_SPORE  - 1] = gMoveDescription_CottonSpore,
    [MOVE_REVERSAL      - 1] = gMoveDescription_Reversal,
    [MOVE_SPITE         - 1] = gMoveDescription_Spite,
    [MOVE_POWDER_SNOW   - 1] = gMoveDescription_PowderSnow,
    [MOVE_PROTECT       - 1] = gMoveDescription_Protect,
    [MOVE_MACH_PUNCH    - 1] = gMoveDescription_MachPunch,
    [MOVE_SCARY_FACE    - 1] = gMoveDescription_ScaryFace,
    [MOVE_FAINT_ATTACK  - 1] = gMoveDescription_FaintAttack,
    [MOVE_SWEET_KISS    - 1] = gMoveDescription_SweetKiss,
    [MOVE_BELLY_DRUM    - 1] = gMoveDescription_BellyDrum,
    [MOVE_SLUDGE_BOMB   - 1] = gMoveDescription_SludgeBomb,
    [MOVE_MUD_SLAP      - 1] = gMoveDescription_MudSlap,
    [MOVE_OCTAZOOKA     - 1] = gMoveDescription_Octazooka,
    [MOVE_SPIKES        - 1] = gMoveDescription_Spikes,
    [MOVE_ZAP_CANNON    - 1] = gMoveDescription_ZapCannon,
    [MOVE_FORESIGHT     - 1] = gMoveDescription_Foresight,
    [MOVE_DESTINY_BOND  - 1] = gMoveDescription_DestinyBond,
    [MOVE_PERISH_SONG   - 1] = gMoveDescription_PerishSong,
    [MOVE_ICY_WIND      - 1] = gMoveDescription_IcyWind,
    [MOVE_DETECT        - 1] = gMoveDescription_Detect,
    [MOVE_BONE_RUSH     - 1] = gMoveDescription_BoneRush,
    [MOVE_LOCK_ON       - 1] = gMoveDescription_LockOn,
    [MOVE_OUTRAGE       - 1] = gMoveDescription_Outrage,
    [MOVE_SANDSTORM     - 1] = gMoveDescription_Sandstorm,
    [MOVE_GIGA_DRAIN    - 1] = gMoveDescription_GigaDrain,
    [MOVE_ENDURE        - 1] = gMoveDescription_Endure,
    [MOVE_CHARM         - 1] = gMoveDescription_Charm,
    [MOVE_ROLLOUT       - 1] = gMoveDescription_Rollout,
    [MOVE_FALSE_SWIPE   - 1] = gMoveDescription_FalseSwipe,
    [MOVE_SWAGGER       - 1] = gMoveDescription_Swagger,
    [MOVE_MILK_DRINK    - 1] = gMoveDescription_MilkDrink,
    [MOVE_SPARK         - 1] = gMoveDescription_Spark,
    [MOVE_FURY_CUTTER   - 1] = gMoveDescription_FuryCutter,
    [MOVE_STEEL_WING    - 1] = gMoveDescription_SteelWing,
    [MOVE_MEAN_LOOK     - 1] = gMoveDescription_MeanLook,
    [MOVE_ATTRACT       - 1] = gMoveDescription_Attract,
    [MOVE_SLEEP_TALK    - 1] = gMoveDescription_SleepTalk,
    [MOVE_HEAL_BELL     - 1] = gMoveDescription_HealBell,
    [MOVE_RETURN        - 1] = gMoveDescription_Return,
    [MOVE_PRESENT       - 1] = gMoveDescription_Present,
    [MOVE_FRUSTRATION   - 1] = gMoveDescription_Frustration,
    [MOVE_SAFEGUARD     - 1] = gMoveDescription_Safeguard,
    [MOVE_PAIN_SPLIT    - 1] = gMoveDescription_PainSplit,
    [MOVE_SACRED_FIRE   - 1] = gMoveDescription_SacredFire,
    [MOVE_MAGNITUDE     - 1] = gMoveDescription_Magnitude,
    [MOVE_DYNAMIC_PUNCH - 1] = gMoveDescription_DynamicPunch,
    [MOVE_MEGAHORN      - 1] = gMoveDescription_Megahorn,
    [MOVE_DRAGON_BREATH - 1] = gMoveDescription_DragonBreath,
    [MOVE_BATON_PASS    - 1] = gMoveDescription_BatonPass,
    [MOVE_ENCORE        - 1] = gMoveDescription_Encore,
    [MOVE_PURSUIT       - 1] = gMoveDescription_Pursuit,
    [MOVE_RAPID_SPIN    - 1] = gMoveDescription_RapidSpin,
    [MOVE_SWEET_SCENT   - 1] = gMoveDescription_SweetScent,
    [MOVE_IRON_TAIL     - 1] = gMoveDescription_IronTail,
    [MOVE_METAL_CLAW    - 1] = gMoveDescription_MetalClaw,
    [MOVE_VITAL_THROW   - 1] = gMoveDescription_VitalThrow,
    [MOVE_MORNING_SUN   - 1] = gMoveDescription_MorningSun,
    [MOVE_SYNTHESIS     - 1] = gMoveDescription_Synthesis,
    [MOVE_MOONLIGHT     - 1] = gMoveDescription_Moonlight,
    [MOVE_HIDDEN_POWER  - 1] = gMoveDescription_HiddenPower,
    [MOVE_CROSS_CHOP    - 1] = gMoveDescription_CrossChop,
    [MOVE_TWISTER       - 1] = gMoveDescription_Twister,
    [MOVE_RAIN_DANCE    - 1] = gMoveDescription_RainDance,
    [MOVE_SUNNY_DAY     - 1] = gMoveDescription_SunnyDay,
    [MOVE_CRUNCH        - 1] = gMoveDescription_Crunch,
    [MOVE_MIRROR_COAT   - 1] = gMoveDescription_MirrorCoat,
    [MOVE_PSYCH_UP      - 1] = gMoveDescription_PsychUp,
    [MOVE_EXTREME_SPEED - 1] = gMoveDescription_ExtremeSpeed,
    [MOVE_ANCIENT_POWER - 1] = gMoveDescription_AncientPower,
    [MOVE_SHADOW_BALL   - 1] = gMoveDescription_ShadowBall,
    [MOVE_FUTURE_SIGHT  - 1] = gMoveDescription_FutureSight,
    [MOVE_ROCK_SMASH    - 1] = gMoveDescription_RockSmash,
    [MOVE_WHIRLPOOL     - 1] = gMoveDescription_Whirlpool,
    [MOVE_BEAT_UP       - 1] = gMoveDescription_BeatUp,
    [MOVE_FAKE_OUT      - 1] = gMoveDescription_FakeOut,
    [MOVE_UPROAR        - 1] = gMoveDescription_Uproar,
    [MOVE_STOCKPILE     - 1] = gMoveDescription_Stockpile,
    [MOVE_SPIT_UP       - 1] = gMoveDescription_SpitUp,
    [MOVE_SWALLOW       - 1] = gMoveDescription_Swallow,
    [MOVE_HEAT_WAVE     - 1] = gMoveDescription_HeatWave,
    [MOVE_HAIL          - 1] = gMoveDescription_Hail,
    [MOVE_TORMENT       - 1] = gMoveDescription_Torment,
    [MOVE_FLATTER       - 1] = gMoveDescription_Flatter,
    [MOVE_WILL_O_WISP   - 1] = gMoveDescription_WillOWisp,
    [MOVE_MEMENTO       - 1] = gMoveDescription_Memento,
    [MOVE_FACADE        - 1] = gMoveDescription_Facade,
    [MOVE_FOCUS_PUNCH   - 1] = gMoveDescription_FocusPunch,
    [MOVE_SMELLING_SALT - 1] = gMoveDescription_SmellingSalt,
    [MOVE_FOLLOW_ME     - 1] = gMoveDescription_FollowMe,
    [MOVE_NATURE_POWER  - 1] = gMoveDescription_NaturePower,
    [MOVE_CHARGE        - 1] = gMoveDescription_Charge,
    [MOVE_TAUNT         - 1] = gMoveDescription_Taunt,
    [MOVE_HELPING_HAND  - 1] = gMoveDescription_HelpingHand,
    [MOVE_TRICK         - 1] = gMoveDescription_Trick,
    [MOVE_ROLE_PLAY     - 1] = gMoveDescription_RolePlay,
    [MOVE_WISH          - 1] = gMoveDescription_Wish,
    [MOVE_ASSIST        - 1] = gMoveDescription_Assist,
    [MOVE_INGRAIN       - 1] = gMoveDescription_Ingrain,
    [MOVE_SUPERPOWER    - 1] = gMoveDescription_Superpower,
    [MOVE_MAGIC_COAT    - 1] = gMoveDescription_MagicCoat,
    [MOVE_RECYCLE       - 1] = gMoveDescription_Recycle,
    [MOVE_REVENGE       - 1] = gMoveDescription_Revenge,
    [MOVE_BRICK_BREAK   - 1] = gMoveDescription_BrickBreak,
    [MOVE_YAWN          - 1] = gMoveDescription_Yawn,
    [MOVE_KNOCK_OFF     - 1] = gMoveDescription_KnockOff,
    [MOVE_ENDEAVOR      - 1] = gMoveDescription_Endeavor,
    [MOVE_ERUPTION      - 1] = gMoveDescription_Eruption,
    [MOVE_SKILL_SWAP    - 1] = gMoveDescription_SkillSwap,
    [MOVE_IMPRISON      - 1] = gMoveDescription_Imprison,
    [MOVE_REFRESH       - 1] = gMoveDescription_Refresh,
    [MOVE_GRUDGE        - 1] = gMoveDescription_Grudge,
    [MOVE_SNATCH        - 1] = gMoveDescription_Snatch,
    [MOVE_SECRET_POWER  - 1] = gMoveDescription_SecretPower,
    [MOVE_DIVE          - 1] = gMoveDescription_Dive,
    [MOVE_ARM_THRUST    - 1] = gMoveDescription_ArmThrust,
    [MOVE_CAMOUFLAGE    - 1] = gMoveDescription_Camouflage,
    [MOVE_TAIL_GLOW     - 1] = gMoveDescription_TailGlow,
    [MOVE_LUSTER_PURGE  - 1] = gMoveDescription_LusterPurge,
    [MOVE_MIST_BALL     - 1] = gMoveDescription_MistBall,
    [MOVE_FEATHER_DANCE - 1] = gMoveDescription_FeatherDance,
    [MOVE_TEETER_DANCE  - 1] = gMoveDescription_TeeterDance,
    [MOVE_BLAZE_KICK    - 1] = gMoveDescription_BlazeKick,
    [MOVE_MUD_SPORT     - 1] = gMoveDescription_MudSport,
    [MOVE_ICE_BALL      - 1] = gMoveDescription_IceBall,
    [MOVE_NEEDLE_ARM    - 1] = gMoveDescription_NeedleArm,
    [MOVE_SLACK_OFF     - 1] = gMoveDescription_SlackOff,
    [MOVE_HYPER_VOICE   - 1] = gMoveDescription_HyperVoice,
    [MOVE_POISON_FANG   - 1] = gMoveDescription_PoisonFang,
    [MOVE_CRUSH_CLAW    - 1] = gMoveDescription_CrushClaw,
    [MOVE_BLAST_BURN    - 1] = gMoveDescription_BlastBurn,
    [MOVE_HYDRO_CANNON  - 1] = gMoveDescription_HydroCannon,
    [MOVE_METEOR_MASH   - 1] = gMoveDescription_MeteorMash,
    [MOVE_ASTONISH      - 1] = gMoveDescription_Astonish,
    [MOVE_WEATHER_BALL  - 1] = gMoveDescription_WeatherBall,
    [MOVE_AROMATHERAPY  - 1] = gMoveDescription_Aromatherapy,
    [MOVE_FAKE_TEARS    - 1] = gMoveDescription_FakeTears,
    [MOVE_AIR_CUTTER    - 1] = gMoveDescription_AirCutter,
    [MOVE_OVERHEAT      - 1] = gMoveDescription_Overheat,
    [MOVE_ODOR_SLEUTH   - 1] = gMoveDescription_OdorSleuth,
    [MOVE_ROCK_TOMB     - 1] = gMoveDescription_RockTomb,
    [MOVE_SILVER_WIND   - 1] = gMoveDescription_SilverWind,
    [MOVE_METAL_SOUND   - 1] = gMoveDescription_MetalSound,
    [MOVE_GRASS_WHISTLE - 1] = gMoveDescription_GrassWhistle,
    [MOVE_TICKLE        - 1] = gMoveDescription_Tickle,
    [MOVE_COSMIC_POWER  - 1] = gMoveDescription_CosmicPower,
    [MOVE_WATER_SPOUT   - 1] = gMoveDescription_WaterSpout,
    [MOVE_SIGNAL_BEAM   - 1] = gMoveDescription_SignalBeam,
    [MOVE_SHADOW_PUNCH  - 1] = gMoveDescription_ShadowPunch,
    [MOVE_EXTRASENSORY  - 1] = gMoveDescription_Extrasensory,
    [MOVE_SKY_UPPERCUT  - 1] = gMoveDescription_SkyUppercut,
    [MOVE_SAND_TOMB     - 1] = gMoveDescription_SandTomb,
    [MOVE_SHEER_COLD    - 1] = gMoveDescription_SheerCold,
    [MOVE_MUDDY_WATER   - 1] = gMoveDescription_MuddyWater,
    [MOVE_BULLET_SEED   - 1] = gMoveDescription_BulletSeed,
    [MOVE_AERIAL_ACE    - 1] = gMoveDescription_AerialAce,
    [MOVE_ICICLE_SPEAR  - 1] = gMoveDescription_IcicleSpear,
    [MOVE_IRON_DEFENSE  - 1] = gMoveDescription_IronDefense,
    [MOVE_BLOCK         - 1] = gMoveDescription_Block,
    [MOVE_HOWL          - 1] = gMoveDescription_Howl,
    [MOVE_DRAGON_CLAW   - 1] = gMoveDescription_DragonClaw,
    [MOVE_FRENZY_PLANT  - 1] = gMoveDescription_FrenzyPlant,
    [MOVE_BULK_UP       - 1] = gMoveDescription_BulkUp,
    [MOVE_BOUNCE        - 1] = gMoveDescription_Bounce,
    [MOVE_MUD_SHOT      - 1] = gMoveDescription_MudShot,
    [MOVE_POISON_TAIL   - 1] = gMoveDescription_PoisonTail,
    [MOVE_COVET         - 1] = gMoveDescription_Covet,
    [MOVE_VOLT_TACKLE   - 1] = gMoveDescription_VoltTackle,
    [MOVE_MAGICAL_LEAF  - 1] = gMoveDescription_MagicalLeaf,
    [MOVE_WATER_SPORT   - 1] = gMoveDescription_WaterSport,
    [MOVE_CALM_MIND     - 1] = gMoveDescription_CalmMind,
    [MOVE_LEAF_BLADE    - 1] = gMoveDescription_LeafBlade,
    [MOVE_DRAGON_DANCE  - 1] = gMoveDescription_DragonDance,
    [MOVE_ROCK_BLAST    - 1] = gMoveDescription_RockBlast,
    [MOVE_SHOCK_WAVE    - 1] = gMoveDescription_ShockWave,
    [MOVE_WATER_PULSE   - 1] = gMoveDescription_WaterPulse,
    [MOVE_DOOM_DESIRE   - 1] = gMoveDescription_DoomDesire,
    [MOVE_PSYCHO_BOOST  - 1] = gMoveDescription_PsychoBoost,
};
