Route11_EastEntrance_2F_Text_GiveItemfinderIfCaught30::
    .string "Hi! Remember me?\n"
    .string "I'm PROF.OAK's AIDE!\p"
    .string "If you caught {STR_VAR_1} kinds\n"
    .string "of POKéMON, I'm supposed to\l"
    .string "give you an ITEMFINDER!\p"
    .string "So, {PLAYER}!\p"
    .string "Have you caught at least\n"
    .string "{STR_VAR_1} kinds of POKéMON?$"

Route11_EastEntrance_2F_Text_GreatHereYouGo::
    .string "Great! You have caught or owned\n"
    .string "{STR_VAR_3} kinds of POKéMON!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"

Route11_EastEntrance_2F_Text_ReceivedItemfinderFromAide::
    .string "{PLAYER} received the {STR_VAR_2}\n"
    .string "from the AIDE.$"

Route11_EastEntrance_2F_Text_ExplainItemfinder::
    .string "There are items on the ground that\n"
    .string "may be hidden from view.\p"
    .string "Use the ITEMFINDER to detect any\n"
    .string "hidden items close to you.\p"
    .string "The machine is a bit limited.\n"
    .string "It can't pinpoint item locations.\p"
    .string "What it does is show the direction\n"
    .string "where the item is.\p"
    .string "Use it to get your bearings, then\n"
    .string "search the suspect area by hand.$"

Route11_EastEntrance_2F_Text_BigMonAsleepOnRoad::
    .string "Looked into the binoculars.\n"
    .string "A big POKéMON is asleep on a road!$"

Route11_EastEntrance_2F_Text_WhatABreathtakingView::
    .string "Looked into the binoculars.\n"
    .string "What a breathtaking view!$"

Route11_EastEntrance_2F_Text_RockTunnelGoodRouteToLavender::
    .string "Looked into the binoculars.\n"
    .string "The only way to get from\n"
    .string "CERULEAN CITY to LAVENDER is\p"
    .string "by way of the ROCK TUNNEL.$"

