CeladonCity_Hotel_Text_ThisHotelIsForPeople::
    .string "POKéMON? No, this\n"
    .string "is a hotel for\l"
    .string "people.\p"
    .string "We're full up.$"

CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend::
    .string "I'm on vacation\n"
    .string "with my brother\l"
    .string "and boy friend.\p"
    .string "CELADON is such a\n"
    .string "pretty city!$"

CeladonCity_Hotel_Text_WhyDidSheBringBrother::
    .string "Why did she bring\n"
    .string "her brother?$"

CeladonCity_Hotel_Text_SisBroughtMeOnVacation::
    .string "My sis brought me\n"
    .string "on this vacation!$"

